import { describe, it, expect } from 'vitest'
import { site, programDetails, pages, auth, app } from '@/content/site'

describe('site content', () => {
  it('has exactly four programs with unique slugs', () => {
    const slugs = site.programs.map(p => p.slug)
    expect(slugs).toEqual(['inquiry', 'essay', 'consulting', 'lab'])
  })
  it('marks inquiry and essay as open', () => {
    expect(site.programs.filter(p => p.status === 'open').map(p => p.slug)).toEqual(['inquiry', 'essay'])
  })
  it('exposes UI copy fields used by components so the homepage never hard-codes strings', () => {
    expect(site.header.login).toBeTruthy()
    expect(site.header.franchise).toBeTruthy()
    expect(site.hero.ctaPrimary).toBeTruthy()
    expect(site.hero.ctaFranchise).toBeTruthy()
    expect(site.sections.programs.eyebrow).toBeTruthy()
    expect(site.sections.programs.title).toBeTruthy()
    expect(site.sections.why.eyebrow).toBeTruthy()
    expect(site.sections.why.title).toBeTruthy()
    expect(site.franchiseCta.title).toBeTruthy()
    expect(site.franchiseCta.body).toBeTruthy()
    expect(site.franchiseCta.button).toBeTruthy()
    expect(site.statusLabel.open).toBeTruthy()
    expect(site.statusLabel.soon).toBeTruthy()
    expect(site.footer.contactLabel).toBeTruthy()
  })
  it('has programDetails for all four program slugs with non-empty headlines', () => {
    const slugs = site.programs.map(p => p.slug)
    for (const slug of slugs) {
      expect(programDetails[slug]).toBeTruthy()
      expect(programDetails[slug].headline).toBeTruthy()
      expect(Array.isArray(programDetails[slug].paragraphs)).toBe(true)
      expect(Array.isArray(programDetails[slug].bullets)).toBe(true)
    }
  })
  it('exposes page copy (ComingSoon, program CTA, franchise form) so pages never hard-code Korean strings', () => {
    expect(pages.comingSoon.eyebrow).toBeTruthy()
    expect(pages.comingSoon.title('테스트')).toContain('테스트')
    expect(pages.comingSoon.body).toBeTruthy()
    expect(pages.comingSoon.back).toBeTruthy()
    expect(pages.program.cta).toBeTruthy()
    expect(pages.franchise.title).toBeTruthy()
    expect(pages.franchise.intro).toBeTruthy()
    expect(pages.franchise.formTitle).toBeTruthy()
    expect(pages.franchise.fields.name.label).toBeTruthy()
    expect(pages.franchise.fields.phone.label).toBeTruthy()
    expect(pages.franchise.fields.phone.placeholder).toBeTruthy()
    expect(pages.franchise.fields.region.label).toBeTruthy()
    expect(pages.franchise.fields.region.placeholder).toBeTruthy()
    expect(pages.franchise.fields.message.label).toBeTruthy()
    expect(pages.franchise.submit).toBeTruthy()
  })
  it('exposes franchise inquiry submission copy (submitting, success, validation errors)', () => {
    expect(pages.franchise.submitting).toBeTruthy()
    expect(pages.franchise.success.title).toBeTruthy()
    expect(pages.franchise.success.body).toBeTruthy()
    expect(pages.franchise.errors.name).toBeTruthy()
    expect(pages.franchise.errors.phone).toBeTruthy()
    expect(pages.franchise.errors.region).toBeTruthy()
    expect(pages.franchise.errors.generic).toBeTruthy()
    expect(pages.franchise.errors.submitFailed).toBeTruthy()
  })
  it('exposes admin inquiries inbox copy (title, columns, status labels, empty state)', () => {
    expect(app.adminInquiries.title).toBeTruthy()
    expect(app.adminInquiries.columns.date).toBeTruthy()
    expect(app.adminInquiries.columns.name).toBeTruthy()
    expect(app.adminInquiries.columns.phone).toBeTruthy()
    expect(app.adminInquiries.columns.region).toBeTruthy()
    expect(app.adminInquiries.columns.message).toBeTruthy()
    expect(app.adminInquiries.columns.status).toBeTruthy()
    expect(app.adminInquiries.statusLabel.new).toBeTruthy()
    expect(app.adminInquiries.statusLabel.contacted).toBeTruthy()
    expect(app.adminInquiries.statusLabel.done).toBeTruthy()
    expect(app.adminInquiries.empty).toBeTruthy()
  })
  it('exposes admin academies copy (list, form, teacher account issuance, errors)', () => {
    expect(app.adminAcademies.listTitle).toBeTruthy()
    expect(app.adminAcademies.columns.code).toBeTruthy()
    expect(app.adminAcademies.columns.name).toBeTruthy()
    expect(app.adminAcademies.columns.region).toBeTruthy()
    expect(app.adminAcademies.columns.teacherCount).toBeTruthy()
    expect(app.adminAcademies.columns.studentCount).toBeTruthy()
    expect(app.adminAcademies.newButton).toBeTruthy()
    expect(app.adminAcademies.form.labels.code).toBeTruthy()
    expect(app.adminAcademies.form.labels.name).toBeTruthy()
    expect(app.adminAcademies.form.labels.region).toBeTruthy()
    expect(app.adminAcademies.form.labels.directorPhone).toBeTruthy()
    expect(app.adminAcademies.form.submit).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.heading).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.formHeading).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.placeholders.name).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.placeholders.email).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.submit).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.submitting).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.issuedNotice).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.labels.id).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.labels.password).toBeTruthy()
    expect(app.adminAcademies.detailMeta.studentCapacity(100)).toContain('100')
    expect(app.adminAcademies.detailMeta.monthlyGradingLimit(300)).toContain('300')
    expect(app.adminAcademies.errors.codeInvalid).toBeTruthy()
    expect(app.adminAcademies.errors.nameRequired).toBeTruthy()
    expect(app.adminAcademies.errors.codeTaken).toBeTruthy()
    expect(app.adminAcademies.errors.teacherMissing).toBeTruthy()
  })
  it('exposes admin standards verification screen copy (filters, summary, columns, actions)', () => {
    expect(app.adminStandards.title).toBeTruthy()
    expect(app.adminStandards.filters.levelLabel).toBeTruthy()
    expect(app.adminStandards.filters.levelAll).toBeTruthy()
    expect(app.adminStandards.filters.subjectLabel).toBeTruthy()
    expect(app.adminStandards.filters.subjectAll).toBeTruthy()
    expect(app.adminStandards.filters.searchLabel).toBeTruthy()
    expect(app.adminStandards.filters.searchPlaceholder).toBeTruthy()
    expect(app.adminStandards.filters.submit).toBeTruthy()
    expect(app.adminStandards.summary(3, 10)).toBe('검증 3 / 10')
    expect(app.adminStandards.columns.code).toBeTruthy()
    expect(app.adminStandards.columns.text).toBeTruthy()
    expect(app.adminStandards.columns.page).toBeTruthy()
    expect(app.adminStandards.columns.status).toBeTruthy()
    expect(app.adminStandards.columns.action).toBeTruthy()
    expect(app.adminStandards.statusLabel.verified).toBeTruthy()
    expect(app.adminStandards.statusLabel.unverified).toBeTruthy()
    expect(app.adminStandards.actions.verify).toBeTruthy()
    expect(app.adminStandards.actions.unverify).toBeTruthy()
    expect(app.adminStandards.empty).toBeTruthy()
    expect(app.adminStandards.pagination.prev).toBeTruthy()
    expect(app.adminStandards.pagination.next).toBeTruthy()
    expect(app.adminStandards.pagination.pageOf(2, 5)).toContain('2')
  })

  it('exposes studio copy (themes list, new theme form, theme detail intro/materials/sets/picker)', () => {
    expect(app.studio.themes.title).toBeTruthy()
    expect(app.studio.themes.newButton).toBeTruthy()
    expect(app.studio.themes.columns.title).toBeTruthy()
    expect(app.studio.themes.columns.level).toBeTruthy()
    expect(app.studio.themes.columns.subjects).toBeTruthy()
    expect(app.studio.themes.columns.setCount).toBeTruthy()
    expect(app.studio.themes.columns.publishedCount).toBeTruthy()
    expect(app.studio.themes.empty).toBeTruthy()
    expect(app.studio.newTheme.title).toBeTruthy()
    expect(app.studio.newTheme.labels.title).toBeTruthy()
    expect(app.studio.newTheme.labels.level).toBeTruthy()
    expect(app.studio.newTheme.labels.grade).toBeTruthy()
    expect(app.studio.newTheme.labels.subjects).toBeTruthy()
    expect(app.studio.newTheme.submit).toBeTruthy()
    expect(app.studio.theme.meta('중', 2)).toContain('중')
    expect(app.studio.theme.addSubjects.heading).toBeTruthy()
    expect(app.studio.theme.addSubjects.help).toBeTruthy()
    expect(app.studio.theme.addSubjects.submit).toBeTruthy()
    expect(app.studio.theme.addSubjects.submitting).toBeTruthy()
    expect(app.studio.theme.addSubjects.saved).toBeTruthy()
    expect(app.studio.theme.addSubjects.nothingToAdd).toBeTruthy()
    expect(app.studio.intro.heading).toBeTruthy()
    expect(app.studio.intro.stateLabel.idle).toBeTruthy()
    expect(app.studio.intro.stateLabel.accepted).toBeTruthy()
    expect(app.studio.intro.mockBadge).toBeTruthy()
    expect(app.studio.intro.actions.generate).toBeTruthy()
    expect(app.studio.intro.actions.review).toBeTruthy()
    expect(app.studio.intro.actions.accept).toBeTruthy()
    expect(app.studio.materials.heading).toBeTruthy()
    expect(app.studio.materials.submit).toBeTruthy()
    expect(app.studio.charts.count).toBeTruthy()
    expect(app.studio.charts.relative).toBeTruthy()
    expect(app.studio.charts.value).toBeTruthy()
    expect(app.studio.sets.heading).toBeTruthy()
    expect(app.studio.sets.statusLabel.draft).toBeTruthy()
    expect(app.studio.sets.statusLabel.review).toBeTruthy()
    expect(app.studio.sets.statusLabel.published).toBeTruthy()
    expect(app.studio.sets.progress(2)).toContain('2/5')
    expect(app.studio.picker.subjectLabel).toBeTruthy()
    expect(app.studio.picker.searchPlaceholder).toBeTruthy()
    expect(app.studio.picker.selectedCount(3)).toContain('3')
    expect(app.studio.picker.unverifiedWarning(['초2사04-01'])).toContain('초2사04-01')
    expect(app.studio.picker.submit).toBeTruthy()
    expect(app.studio.picker.uncategorized).toBeTruthy()
  })

  it('exposes studio wizard copy (stage names, state/action labels, JSON edit, key question, error texts)', () => {
    expect(app.studio.wizard.backToTheme).toBeTruthy()
    expect(app.studio.wizard.versionLabel(2)).toContain('2')
    expect(app.studio.wizard.stageNames[2]).toBeTruthy()
    expect(app.studio.wizard.stageNames[3]).toBeTruthy()
    expect(app.studio.wizard.stageNames[4]).toBeTruthy()
    expect(app.studio.wizard.stageNames[5]).toBeTruthy()
    expect(app.studio.wizard.stageNames[6]).toBeTruthy()
    expect(app.studio.wizard.stageNames[7]).toBe('안내장 틀')
    expect(app.studio.wizard.stage7.summary(5, 2)).toBe('차시 5개 · 서·논술형 차시 문구 2개')
    expect(app.studio.wizard.stage2.goal('상대도수를 구할 수 있다.', '과정·기능')).toContain('과정·기능')
    expect(app.studio.publish.blockers.stageNotAccepted(7)).toContain('7단계')
    expect(app.studio.wizard.stateLabel.accepted).toBeTruthy()
    expect(app.studio.wizard.actions.generate).toBeTruthy()
    expect(app.studio.wizard.actions.review).toBeTruthy()
    expect(app.studio.wizard.actions.accept).toBeTruthy()
    expect(app.studio.wizard.actions.runDefaults).toBeTruthy()
    expect(app.studio.wizard.actions.editJson).toBeTruthy()
    expect(app.studio.wizard.actions.save).toBeTruthy()
    expect(app.studio.wizard.keyQuestion.heading).toBeTruthy()
    expect(app.studio.wizard.keyQuestion.select).toBeTruthy()
    expect(app.studio.wizard.stage3.columns.no).toBeTruthy()
    expect(app.studio.wizard.stage4.previewHeading).toBeTruthy()
    expect(app.studio.wizard.stage5.pointsLabel(3)).toContain('3')
    expect(app.studio.wizard.stage5.boundary(4, 15, 18, '중')).toBe('4등급: 15~18 (중)')
    expect(app.studio.wizard.stage5.exemplarCount(3, 4)).toBe('3번 문항 예시답안 4개')
    expect(app.studio.wizard.errors.tooManyFailures).toBeTruthy()
    expect(app.studio.wizard.stage6.termsCount(5)).toContain('5')
    expect(app.studio.wizard.errors.invalidJson).toBeTruthy()
    expect(app.studio.wizard.errors.invalidShape('bad')).toContain('bad')
    expect(app.studio.wizard.errors.keyQuestionInvalid).toBeTruthy()
    expect(app.studio.wizard.errors.prevNotAccepted).toBeTruthy()
    expect(app.studio.wizard.errors.tooFewStandards).toBeTruthy()
    expect(app.studio.wizard.prevStageHint).toBeTruthy()
  })

  it('exposes attachments copy (heading, target labels, upload/delete actions, errors)', () => {
    expect(app.studio.attachments.heading).toBeTruthy()
    expect(app.studio.attachments.description).toBeTruthy()
    expect(app.studio.attachments.targetLabel).toBeTruthy()
    expect(app.studio.attachments.materialLabel('A')).toContain('A')
    expect(app.studio.attachments.lessonLabel(3)).toContain('3')
    expect(app.studio.attachments.noTargets).toBeTruthy()
    expect(app.studio.attachments.fileLabel).toBeTruthy()
    expect(app.studio.attachments.upload).toBeTruthy()
    expect(app.studio.attachments.uploading).toBeTruthy()
    expect(app.studio.attachments.empty).toBeTruthy()
    expect(app.studio.attachments.delete).toBeTruthy()
    expect(app.studio.attachments.thumbnailAlt('자료 A', 2)).toContain('자료 A')
    expect(app.studio.attachments.thumbnailAlt('자료 A', 2)).toContain('2')
    expect(app.studio.attachments.errors.invalidTarget).toBeTruthy()
    expect(app.studio.attachments.errors.invalidUrl).toBeTruthy()
    expect(app.studio.attachments.errors.itemNotFound).toBeTruthy()
    expect(app.studio.attachments.errors.invalidShape).toBeTruthy()
    expect(app.studio.attachments.errors.saveFailed).toBeTruthy()
    expect(app.studio.attachments.errors.uploadFailed).toBeTruthy()
    expect(app.studio.attachments.errors.fileTooLarge).toBeTruthy()
    expect(app.studio.attachments.errors.invalidType).toBeTruthy()
  })

  it('exposes studio publish copy (tabs, current/next version, blockers, success, errors)', () => {
    expect(app.studio.publish.tabs.wizard).toBeTruthy()
    expect(app.studio.publish.tabs.preview).toBeTruthy()
    expect(app.studio.publish.heading).toBeTruthy()
    expect(app.studio.publish.currentVersionLabel(1)).toContain('1')
    expect(app.studio.publish.nextVersionLabel(2)).toContain('2')
    expect(app.studio.publish.button).toBeTruthy()
    expect(app.studio.publish.busy).toBeTruthy()
    expect(app.studio.publish.success(3)).toContain('3')
    expect(app.studio.publish.blockersHeading).toBeTruthy()
    expect(app.studio.publish.blockers.stageNotAccepted(3)).toContain('3')
    expect(app.studio.publish.blockers.unverifiedStandard('[9수04-02]')).toContain('[9수04-02]')
    expect(app.studio.publish.blockers.noKeyQuestion).toBeTruthy()
    expect(app.studio.publish.blockers.unknown).toBeTruthy()
    expect(app.studio.publish.errors.forbidden).toBeTruthy()
    expect(app.studio.publish.errors.saveFailed).toBeTruthy()
    expect(app.studio.sets.statusLabel.retired).toBeTruthy()
  })

  it('exposes packageView copy for every section (cover, standards, lessons/quiz, teacher guide, assessment, rubrics, grade boundaries, exemplars, feedback)', () => {
    expect(app.packageView.cover.versionLabel(2)).toContain('2')
    expect(app.packageView.cover.publishedAtLabel).toBeTruthy()
    expect(app.packageView.cover.meta('중', 2, '수학')).toContain('중')
    expect(app.packageView.intro).toBeTruthy()
    expect(app.packageView.standardsHeading).toBeTruthy()
    expect(app.packageView.reconstructionHeading).toBeTruthy()
    expect(app.packageView.learningGoalsHeading).toBeTruthy()
    expect(app.packageView.keyQuestionHeading).toBeTruthy()
    expect(app.packageView.materialsHeading).toBeTruthy()
    expect(app.packageView.materials.idLabel).toBeTruthy()
    expect(app.packageView.materials.imagesAlt('자료 A', 1)).toContain('자료 A')
    expect(app.packageView.lessonsHeading).toBeTruthy()
    expect(app.packageView.lessons.columns.no).toBeTruthy()
    expect(app.packageView.lessons.noAssessment).toBeTruthy()
    expect(app.packageView.lessons.flow.intro).toBeTruthy()
    expect(app.packageView.lessons.flow.main).toBeTruthy()
    expect(app.packageView.lessons.flow.wrapup).toBeTruthy()
    expect(app.packageView.lessons.materialsLabel).toBeTruthy()
    expect(app.packageView.lessons.quizHeading).toBeTruthy()
    expect(app.packageView.lessons.quiz.typeLabel.choice).toBeTruthy()
    expect(app.packageView.lessons.quiz.typeLabel.short).toBeTruthy()
    expect(app.packageView.lessons.quiz.answerLabel).toBeTruthy()
    expect(app.packageView.lessons.quiz.explanationLabel).toBeTruthy()
    expect(app.packageView.lessons.quiz.answersHidden).toBeTruthy()
    expect(app.packageView.lessons.imagesAlt(3, 1)).toContain('3')
    expect(app.packageView.teacherGuideHeading).toBeTruthy()
    expect(app.packageView.teacherGuide.generalHeading).toBeTruthy()
    expect(app.packageView.teacherGuide.materialsLabel).toBeTruthy()
    expect(app.packageView.teacherGuide.scheduleLabel).toBeTruthy()
    expect(app.packageView.teacherGuide.purposeLabel).toBeTruthy()
    expect(app.packageView.teacherGuide.glossaryHeading).toBeTruthy()
    expect(app.packageView.teacherGuide.perLessonHeading).toBeTruthy()
    expect(app.packageView.teacherGuide.lessonLabel(2)).toContain('2')
    expect(app.packageView.assessmentHeading).toBeTruthy()
    expect(app.packageView.assessment.kindLabel.서술형).toBeTruthy()
    expect(app.packageView.assessment.kindLabel.논술형).toBeTruthy()
    expect(app.packageView.assessment.lessonLabel(1)).toContain('1')
    expect(app.packageView.assessment.pointsLabel(5)).toContain('5')
    expect(app.packageView.assessment.conditions.lengthLabel).toBeTruthy()
    expect(app.packageView.assessment.conditions.requiredLabel).toBeTruthy()
    expect(app.packageView.assessment.conditions.formatLabel).toBeTruthy()
    expect(app.packageView.rubricHeading).toBeTruthy()
    expect(app.packageView.shortRubric.pointsLabel).toBeTruthy()
    expect(app.packageView.shortRubric.expectationLabel).toBeTruthy()
    expect(app.packageView.shortRubric.exampleLabel).toBeTruthy()
    expect(app.packageView.extendedRubric.criteriaLabel).toBeTruthy()
    expect(app.packageView.extendedRubric.bandLabel(4)).toContain('4')
    expect(app.packageView.gradeBoundariesHeading).toBeTruthy()
    expect(app.packageView.gradeBoundaries.gradeLabel).toBeTruthy()
    expect(app.packageView.gradeBoundaries.rangeLabel).toBeTruthy()
    expect(app.packageView.gradeBoundaries.bandLabel).toBeTruthy()
    expect(app.packageView.exemplarsHeading).toBeTruthy()
    expect(app.packageView.exemplars.levelLabel.상).toBeTruthy()
    expect(app.packageView.exemplars.scoresLabel).toBeTruthy()
    expect(app.packageView.exemplars.totalLabel(10)).toContain('10')
    expect(app.packageView.exemplars.gradeLabel(3)).toContain('3')
    expect(app.packageView.feedbackTemplatesHeading).toBeTruthy()
    expect(app.packageView.feedbackLevels.상).toBeTruthy()
    expect(app.packageView.feedbackLevels.중).toBeTruthy()
    expect(app.packageView.feedbackLevels.하).toBeTruthy()
    expect(app.packageView.generatedWithHeading).toBeTruthy()
  })

  it('exposes the v2 student answer copy (paper-answer notice, numbered condition label, paper-only error)', () => {
    expect(app.classroom.student.paperAnswer).toContain('종이')
    expect(app.classroom.student.conditionItem(2)).toContain('2')
    expect(app.classroom.student.errors.paperOnly).toBeTruthy()
  })

  it('exposes packageView print copy (문제지 인쇄 button, paper answer box, 이름·날짜 line)', () => {
    const p = app.packageView.print
    expect(p.button).toBe('문제지 인쇄')
    expect(p.paperBox).toContain('종이 답안')
    // 자료·문항 카드의 종이 답안 배지(answerMode.paper)와 겹치지 않아야 기존 개수 검사가 유지된다
    expect(p.paperBox).not.toContain(app.packageView.assessment.conditions.answerMode.paper)
    expect(p.studentLine.name).toBe('이름')
    expect(p.studentLine.date).toBe('날짜')
  })

  it('exposes packageView v2 copy (unit plan, lessons v2, item card, rubric, notice plan, answers toggle)', () => {
    const c = app.packageView
    expect(c.unitPlan.placement('논술형', 5)).toContain('5')
    expect(c.lessons.timeLabel(10, 40, 10)).toContain('40')
    expect(c.lessons.stepLabel('개념·활동', 20)).toContain('20')
    expect(c.lessons.worksheetTier('기본', 'D~E')).toContain('D~E')
    expect(c.assessment.conditions.itemNo(3)).toContain('3')
    expect(c.assessment.conditions.answerMode.paper).toBeTruthy()
    expect(c.assessment.conditions.answerMode.screen).toBeTruthy()
    expect(c.rubric.criterionLabel('요소', 4)).toContain('4')
    expect(c.materials.sourceLabel.공개).toBeTruthy()
    expect(c.materials.roleLabel.context).toBeTruthy()
    expect(c.noticePlanHeading).toBeTruthy()
    expect(c.answersToggle).toBeTruthy()
  })

  it('exposes teacherItems copy (title, filters, card, empty, detail)', () => {
    expect(app.teacherItems.title).toBeTruthy()
    expect(app.teacherItems.filters.levelLabel).toBeTruthy()
    expect(app.teacherItems.filters.levelAll).toBeTruthy()
    expect(app.teacherItems.filters.subjectLabel).toBeTruthy()
    expect(app.teacherItems.filters.subjectAll).toBeTruthy()
    expect(app.teacherItems.filters.submit).toBeTruthy()
    expect(app.teacherItems.card.versionLabel(2)).toContain('2')
    expect(app.teacherItems.card.meta('중', 2)).toContain('중')
    expect(app.teacherItems.card.open).toBeTruthy()
    expect(app.teacherItems.empty).toBeTruthy()
    expect(app.teacherItems.detail.backToList).toBeTruthy()
    expect(app.teacherItems.detail.notFoundTitle).toBeTruthy()
  })

  it('exposes login page copy so the login form never hard-codes Korean strings', () => {
    expect(auth.login.title).toBeTruthy()
    expect(auth.login.subtitle).toBeTruthy()
    expect(auth.login.idLabel).toBeTruthy()
    expect(auth.login.passwordLabel).toBeTruthy()
    expect(auth.login.submit).toBeTruthy()
    expect(auth.login.submitting).toBeTruthy()
    expect(auth.login.errors.missing).toBeTruthy()
    expect(auth.login.errors.invalid).toBeTruthy()
  })
  it('exposes app shell copy (role labels, nav, logout, dashboard headings) for admin/teacher/student', () => {
    expect(app.roleLabel.admin).toBeTruthy()
    expect(app.roleLabel.teacher).toBeTruthy()
    expect(app.roleLabel.student).toBeTruthy()
    expect(app.logout).toBeTruthy()

    expect(app.nav.admin.map(n => n.href)).toEqual(['/admin', '/admin/academies', '/admin/items', '/admin/inquiries', '/admin/standards'])
    expect(app.nav.teacher.map(n => n.href)).toEqual(['/teacher', '/teacher/students', '/teacher/items', '/teacher/assignments'])
    expect(app.nav.student.map(n => n.href)).toEqual(['/student'])

    for (const role of ['admin', 'teacher', 'student'] as const) {
      for (const item of app.nav[role]) {
        expect(item.label).toBeTruthy()
      }
      expect(app.dashboard[role].title).toBeTruthy()
      expect(app.dashboard[role].body).toBeTruthy()
    }
  })
})
