import { describe, it, expect } from 'vitest'
import { site, programDetails, pages, auth, app } from '@/content/site'

describe('site content', () => {
  it('has exactly four programs with unique slugs', () => {
    const slugs = site.programs.map(p => p.slug)
    expect(slugs).toEqual(['inquiry', 'essay', 'consulting', 'lab'])
  })
  it('marks inquiry and essay as open', () => {
    expect(site.programs.filter(p => p.status === 'open').map(p => p.slug)).toEqual(['inquiry', 'essay'])
  })
  it('exposes UI copy fields used by components so the homepage never hard-codes strings', () => {
    expect(site.header.login).toBeTruthy()
    expect(site.header.franchise).toBeTruthy()
    expect(site.hero.ctaPrimary).toBeTruthy()
    expect(site.hero.ctaFranchise).toBeTruthy()
    expect(site.sections.programs.eyebrow).toBeTruthy()
    expect(site.sections.programs.title).toBeTruthy()
    expect(site.sections.why.eyebrow).toBeTruthy()
    expect(site.sections.why.title).toBeTruthy()
    expect(site.franchiseCta.title).toBeTruthy()
    expect(site.franchiseCta.body).toBeTruthy()
    expect(site.franchiseCta.button).toBeTruthy()
    expect(site.statusLabel.open).toBeTruthy()
    expect(site.statusLabel.soon).toBeTruthy()
    expect(site.footer.contactLabel).toBeTruthy()
  })
  it('has programDetails for all four program slugs with non-empty headlines', () => {
    const slugs = site.programs.map(p => p.slug)
    for (const slug of slugs) {
      expect(programDetails[slug]).toBeTruthy()
      expect(programDetails[slug].headline).toBeTruthy()
      expect(Array.isArray(programDetails[slug].paragraphs)).toBe(true)
      expect(Array.isArray(programDetails[slug].bullets)).toBe(true)
    }
  })
  it('exposes page copy (ComingSoon, program CTA, franchise form) so pages never hard-code Korean strings', () => {
    expect(pages.comingSoon.eyebrow).toBeTruthy()
    expect(pages.comingSoon.title('테스트')).toContain('테스트')
    expect(pages.comingSoon.body).toBeTruthy()
    expect(pages.comingSoon.back).toBeTruthy()
    expect(pages.program.cta).toBeTruthy()
    expect(pages.franchise.title).toBeTruthy()
    expect(pages.franchise.intro).toBeTruthy()
    expect(pages.franchise.formTitle).toBeTruthy()
    expect(pages.franchise.fields.name.label).toBeTruthy()
    expect(pages.franchise.fields.phone.label).toBeTruthy()
    expect(pages.franchise.fields.phone.placeholder).toBeTruthy()
    expect(pages.franchise.fields.region.label).toBeTruthy()
    expect(pages.franchise.fields.region.placeholder).toBeTruthy()
    expect(pages.franchise.fields.message.label).toBeTruthy()
    expect(pages.franchise.submit).toBeTruthy()
  })
  it('exposes franchise inquiry submission copy (submitting, success, validation errors)', () => {
    expect(pages.franchise.submitting).toBeTruthy()
    expect(pages.franchise.success.title).toBeTruthy()
    expect(pages.franchise.success.body).toBeTruthy()
    expect(pages.franchise.errors.name).toBeTruthy()
    expect(pages.franchise.errors.phone).toBeTruthy()
    expect(pages.franchise.errors.region).toBeTruthy()
    expect(pages.franchise.errors.generic).toBeTruthy()
    expect(pages.franchise.errors.submitFailed).toBeTruthy()
  })
  it('exposes admin inquiries inbox copy (title, columns, status labels, empty state)', () => {
    expect(app.adminInquiries.title).toBeTruthy()
    expect(app.adminInquiries.columns.date).toBeTruthy()
    expect(app.adminInquiries.columns.name).toBeTruthy()
    expect(app.adminInquiries.columns.phone).toBeTruthy()
    expect(app.adminInquiries.columns.region).toBeTruthy()
    expect(app.adminInquiries.columns.message).toBeTruthy()
    expect(app.adminInquiries.columns.status).toBeTruthy()
    expect(app.adminInquiries.statusLabel.new).toBeTruthy()
    expect(app.adminInquiries.statusLabel.contacted).toBeTruthy()
    expect(app.adminInquiries.statusLabel.done).toBeTruthy()
    expect(app.adminInquiries.empty).toBeTruthy()
  })
  it('exposes admin academies copy (list, form, teacher account issuance, errors)', () => {
    expect(app.adminAcademies.listTitle).toBeTruthy()
    expect(app.adminAcademies.columns.code).toBeTruthy()
    expect(app.adminAcademies.columns.name).toBeTruthy()
    expect(app.adminAcademies.columns.region).toBeTruthy()
    expect(app.adminAcademies.columns.teacherCount).toBeTruthy()
    expect(app.adminAcademies.columns.studentCount).toBeTruthy()
    expect(app.adminAcademies.newButton).toBeTruthy()
    expect(app.adminAcademies.form.labels.code).toBeTruthy()
    expect(app.adminAcademies.form.labels.name).toBeTruthy()
    expect(app.adminAcademies.form.labels.region).toBeTruthy()
    expect(app.adminAcademies.form.labels.directorPhone).toBeTruthy()
    expect(app.adminAcademies.form.submit).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.heading).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.formHeading).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.placeholders.name).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.placeholders.email).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.submit).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.submitting).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.issuedNotice).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.labels.id).toBeTruthy()
    expect(app.adminAcademies.teacherAccount.labels.password).toBeTruthy()
    expect(app.adminAcademies.detailMeta.studentCapacity(100)).toContain('100')
    expect(app.adminAcademies.detailMeta.monthlyGradingLimit(300)).toContain('300')
    expect(app.adminAcademies.errors.codeInvalid).toBeTruthy()
    expect(app.adminAcademies.errors.nameRequired).toBeTruthy()
    expect(app.adminAcademies.errors.codeTaken).toBeTruthy()
    expect(app.adminAcademies.errors.teacherMissing).toBeTruthy()
  })
  it('exposes admin standards verification screen copy (filters, summary, columns, actions)', () => {
    expect(app.adminStandards.title).toBeTruthy()
    expect(app.adminStandards.filters.levelLabel).toBeTruthy()
    expect(app.adminStandards.filters.levelAll).toBeTruthy()
    expect(app.adminStandards.filters.subjectLabel).toBeTruthy()
    expect(app.adminStandards.filters.subjectAll).toBeTruthy()
    expect(app.adminStandards.filters.searchLabel).toBeTruthy()
    expect(app.adminStandards.filters.searchPlaceholder).toBeTruthy()
    expect(app.adminStandards.filters.submit).toBeTruthy()
    expect(app.adminStandards.summary(3, 10)).toBe('검증 3 / 10')
    expect(app.adminStandards.columns.code).toBeTruthy()
    expect(app.adminStandards.columns.text).toBeTruthy()
    expect(app.adminStandards.columns.page).toBeTruthy()
    expect(app.adminStandards.columns.status).toBeTruthy()
    expect(app.adminStandards.columns.action).toBeTruthy()
    expect(app.adminStandards.statusLabel.verified).toBeTruthy()
    expect(app.adminStandards.statusLabel.unverified).toBeTruthy()
    expect(app.adminStandards.actions.verify).toBeTruthy()
    expect(app.adminStandards.actions.unverify).toBeTruthy()
    expect(app.adminStandards.empty).toBeTruthy()
    expect(app.adminStandards.pagination.prev).toBeTruthy()
    expect(app.adminStandards.pagination.next).toBeTruthy()
    expect(app.adminStandards.pagination.pageOf(2, 5)).toContain('2')
  })

  it('exposes studio copy (themes list, new theme form, theme detail intro/materials/sets/picker)', () => {
    expect(app.studio.themes.title).toBeTruthy()
    expect(app.studio.themes.newButton).toBeTruthy()
    expect(app.studio.themes.columns.title).toBeTruthy()
    expect(app.studio.themes.columns.level).toBeTruthy()
    expect(app.studio.themes.columns.subjects).toBeTruthy()
    expect(app.studio.themes.columns.setCount).toBeTruthy()
    expect(app.studio.themes.columns.publishedCount).toBeTruthy()
    expect(app.studio.themes.empty).toBeTruthy()
    expect(app.studio.newTheme.title).toBeTruthy()
    expect(app.studio.newTheme.labels.title).toBeTruthy()
    expect(app.studio.newTheme.labels.level).toBeTruthy()
    expect(app.studio.newTheme.labels.grade).toBeTruthy()
    expect(app.studio.newTheme.labels.subjects).toBeTruthy()
    expect(app.studio.newTheme.submit).toBeTruthy()
    expect(app.studio.theme.meta('중', 2)).toContain('중')
    expect(app.studio.intro.heading).toBeTruthy()
    expect(app.studio.intro.stateLabel.idle).toBeTruthy()
    expect(app.studio.intro.stateLabel.accepted).toBeTruthy()
    expect(app.studio.intro.mockBadge).toBeTruthy()
    expect(app.studio.intro.actions.generate).toBeTruthy()
    expect(app.studio.intro.actions.review).toBeTruthy()
    expect(app.studio.intro.actions.accept).toBeTruthy()
    expect(app.studio.materials.heading).toBeTruthy()
    expect(app.studio.materials.submit).toBeTruthy()
    expect(app.studio.charts.count).toBeTruthy()
    expect(app.studio.charts.relative).toBeTruthy()
    expect(app.studio.charts.value).toBeTruthy()
    expect(app.studio.sets.heading).toBeTruthy()
    expect(app.studio.sets.statusLabel.draft).toBeTruthy()
    expect(app.studio.sets.statusLabel.review).toBeTruthy()
    expect(app.studio.sets.statusLabel.published).toBeTruthy()
    expect(app.studio.sets.progress(2)).toContain('2/5')
    expect(app.studio.picker.subjectLabel).toBeTruthy()
    expect(app.studio.picker.searchPlaceholder).toBeTruthy()
    expect(app.studio.picker.selectedCount(3)).toContain('3')
    expect(app.studio.picker.unverifiedWarning(['초2사04-01'])).toContain('초2사04-01')
    expect(app.studio.picker.submit).toBeTruthy()
    expect(app.studio.picker.uncategorized).toBeTruthy()
  })

  it('exposes studio wizard copy (stage names, state/action labels, JSON edit, key question, error texts)', () => {
    expect(app.studio.wizard.backToTheme).toBeTruthy()
    expect(app.studio.wizard.versionLabel(2)).toContain('2')
    expect(app.studio.wizard.stageNames[2]).toBeTruthy()
    expect(app.studio.wizard.stageNames[3]).toBeTruthy()
    expect(app.studio.wizard.stageNames[4]).toBeTruthy()
    expect(app.studio.wizard.stageNames[5]).toBeTruthy()
    expect(app.studio.wizard.stageNames[6]).toBeTruthy()
    expect(app.studio.wizard.stateLabel.accepted).toBeTruthy()
    expect(app.studio.wizard.actions.generate).toBeTruthy()
    expect(app.studio.wizard.actions.review).toBeTruthy()
    expect(app.studio.wizard.actions.accept).toBeTruthy()
    expect(app.studio.wizard.actions.runDefaults).toBeTruthy()
    expect(app.studio.wizard.actions.editJson).toBeTruthy()
    expect(app.studio.wizard.actions.save).toBeTruthy()
    expect(app.studio.wizard.keyQuestion.heading).toBeTruthy()
    expect(app.studio.wizard.keyQuestion.select).toBeTruthy()
    expect(app.studio.wizard.stage3.columns.no).toBeTruthy()
    expect(app.studio.wizard.stage4.previewHeading).toBeTruthy()
    expect(app.studio.wizard.stage5.pointsLabel(3)).toContain('3')
    expect(app.studio.wizard.stage5.boundary(4, 15, 18, '중')).toBe('4등급: 15~18 (중)')
    expect(app.studio.wizard.stage5.exemplar('상', 7)).toBe('상 — 7등급')
    expect(app.studio.wizard.errors.tooManyFailures).toBeTruthy()
    expect(app.studio.wizard.stage6.termsCount(5)).toContain('5')
    expect(app.studio.wizard.errors.invalidJson).toBeTruthy()
    expect(app.studio.wizard.errors.invalidShape('bad')).toContain('bad')
    expect(app.studio.wizard.errors.keyQuestionInvalid).toBeTruthy()
    expect(app.studio.wizard.prevStageHint).toBeTruthy()
  })

  it('exposes attachments copy (heading, target labels, upload/delete actions, errors)', () => {
    expect(app.studio.attachments.heading).toBeTruthy()
    expect(app.studio.attachments.description).toBeTruthy()
    expect(app.studio.attachments.targetLabel).toBeTruthy()
    expect(app.studio.attachments.materialLabel('A')).toContain('A')
    expect(app.studio.attachments.lessonLabel(3)).toContain('3')
    expect(app.studio.attachments.noTargets).toBeTruthy()
    expect(app.studio.attachments.fileLabel).toBeTruthy()
    expect(app.studio.attachments.upload).toBeTruthy()
    expect(app.studio.attachments.uploading).toBeTruthy()
    expect(app.studio.attachments.empty).toBeTruthy()
    expect(app.studio.attachments.delete).toBeTruthy()
    expect(app.studio.attachments.thumbnailAlt('자료 A', 2)).toContain('자료 A')
    expect(app.studio.attachments.thumbnailAlt('자료 A', 2)).toContain('2')
    expect(app.studio.attachments.errors.invalidTarget).toBeTruthy()
    expect(app.studio.attachments.errors.invalidUrl).toBeTruthy()
    expect(app.studio.attachments.errors.itemNotFound).toBeTruthy()
    expect(app.studio.attachments.errors.invalidShape).toBeTruthy()
    expect(app.studio.attachments.errors.saveFailed).toBeTruthy()
    expect(app.studio.attachments.errors.uploadFailed).toBeTruthy()
    expect(app.studio.attachments.errors.fileTooLarge).toBeTruthy()
    expect(app.studio.attachments.errors.invalidType).toBeTruthy()
  })

  it('exposes login page copy so the login form never hard-codes Korean strings', () => {
    expect(auth.login.title).toBeTruthy()
    expect(auth.login.subtitle).toBeTruthy()
    expect(auth.login.idLabel).toBeTruthy()
    expect(auth.login.passwordLabel).toBeTruthy()
    expect(auth.login.submit).toBeTruthy()
    expect(auth.login.submitting).toBeTruthy()
    expect(auth.login.errors.missing).toBeTruthy()
    expect(auth.login.errors.invalid).toBeTruthy()
  })
  it('exposes app shell copy (role labels, nav, logout, dashboard headings) for admin/teacher/student', () => {
    expect(app.roleLabel.admin).toBeTruthy()
    expect(app.roleLabel.teacher).toBeTruthy()
    expect(app.roleLabel.student).toBeTruthy()
    expect(app.logout).toBeTruthy()

    expect(app.nav.admin.map(n => n.href)).toEqual(['/admin', '/admin/academies', '/admin/items', '/admin/inquiries', '/admin/standards'])
    expect(app.nav.teacher.map(n => n.href)).toEqual(['/teacher', '/teacher/students', '/teacher/items', '/teacher/results'])
    expect(app.nav.student.map(n => n.href)).toEqual(['/student'])

    for (const role of ['admin', 'teacher', 'student'] as const) {
      for (const item of app.nav[role]) {
        expect(item.label).toBeTruthy()
      }
      expect(app.dashboard[role].title).toBeTruthy()
      expect(app.dashboard[role].body).toBeTruthy()
    }
  })
})
