export type ProgramSlug = 'inquiry' | 'essay' | 'consulting' | 'lab'

export const site = {
  name: '다빈치스쿨',
  tagline: '스스로 묻고, 탐구하고, 글로 증명하는 아이들',
  intro:
    '다빈치스쿨은 5년간 40권의 탐구보고서 교재로 검증된 수업을 전국 가맹원에 공급하는 교육 본사입니다. 이제 서논술형 수업과 AI 피드백으로 아이의 생각을 글로 완성합니다.',
  metaDescription: '탐구보고서와 서논술형 수업, 전국 가맹원 네트워크 다빈치스쿨',
  stats: [
    { label: '전국 가맹원', value: '40+' },
    { label: '탐구보고서 교재', value: '40권' },
    { label: '누적 수업 기간', value: '5년' },
  ],
  programs: [
    { slug: 'inquiry', name: '탐구보고서', short: '질문에서 보고서까지, 5년 검증된 탐구 수업', status: 'open', accent: 'mint' },
    { slug: 'essay', name: '서논술형 수업', short: '성취기준 기반 문항과 AI 채점·피드백', status: 'open', accent: 'lemon' },
    { slug: 'consulting', name: '대입 컨설팅', short: '탐구 이력을 대입 전략으로', status: 'soon', accent: 'lavender' },
    { slug: 'lab', name: '다빈치랩', short: '자기주도 학습관', status: 'soon', accent: 'mint' },
  ] as const satisfies ReadonlyArray<{ slug: ProgramSlug; name: string; short: string; status: 'open' | 'soon'; accent: 'mint' | 'lemon' | 'lavender' }>,
  why: [
    { title: '교육과정에서 출발', body: '2022 개정 교육과정 성취기준 원문에서 문항을 설계합니다.' },
    { title: '글로 남는 배움', body: '탐구와 논술의 결과가 학생의 글로 축적됩니다.' },
    { title: '원장님과 함께', body: '본사가 문항·지침서·자료를 만들고, 원장님은 수업에 집중합니다.' },
  ],
  contact: { email: 'davincischooloffice@gmail.com' },
  nav: [
    { href: '/programs/inquiry', label: '탐구보고서' },
    { href: '/programs/essay', label: '서논술형' },
    { href: '/programs/consulting', label: '대입 컨설팅' },
    { href: '/programs/lab', label: '다빈치랩' },
  ],
  header: { login: '로그인', franchise: '가맹문의' },
  hero: { ctaPrimary: '서논술형 수업 보기', ctaFranchise: '가맹문의' },
  sections: {
    programs: { eyebrow: 'PROGRAMS', title: '다빈치스쿨의 네 가지 수업' },
    why: { eyebrow: 'WHY DAVINCI', title: '왜 다빈치인가' },
  },
  franchiseCta: {
    title: '우리 지역에 다빈치스쿨을 열고 싶다면',
    body: '본사가 교재·문항·교사용 지침서를 준비합니다.',
    button: '가맹 안내 보기',
  },
  statusLabel: { open: '운영 중', soon: '준비 중' },
  footer: { contactLabel: '문의' },
}

export const programDetails: Record<ProgramSlug, { headline: string; paragraphs: string[]; bullets: string[] }> = {
  inquiry: {
    headline: '질문에서 보고서까지, 스스로 완성하는 탐구',
    paragraphs: ['5년간 40권의 교재로 다듬어진 탐구보고서 수업입니다. 학생은 질문을 세우고, 자료를 모으고, 보고서로 정리하는 과정을 학년별로 반복합니다.'],
    bullets: ['초·중·고 학년별 교재 40권', '주제 선정 → 자료 조사 → 보고서 작성의 3단계', '원장님용 수업 지도안 제공'],
  },
  essay: {
    headline: '성취기준에서 출발하는 서논술형 수업과 AI 피드백',
    paragraphs: ['2022 개정 교육과정 성취기준 원문에서 문항을 설계합니다. 학생이 답안을 제출하면 루브릭에 따라 AI가 채점하고, 잘한 점과 보완할 점을 나누어 피드백합니다.', '한 가지 대주제를 국어·영어·수학·과학·사회가 함께 다루는 융합(STEAM) 방식으로 문항을 구성합니다.'],
    bullets: ['초·중·고 × 국·영·수·과·사·한국사', '루브릭 기반 AI 채점, 30초 안에 피드백', '교사용 지침서·차시 설계·예시답안 제공'],
  },
  consulting: { headline: '탐구 이력을 대입 전략으로', paragraphs: ['준비 중입니다.'], bullets: [] },
  lab: { headline: '자기주도 학습관 다빈치랩', paragraphs: ['준비 중입니다.'], bullets: [] },
}

export const auth = {
  login: {
    title: '로그인',
    subtitle: '원장님·학생·관리자 모두 여기서 로그인합니다.',
    idLabel: '아이디 또는 이메일',
    passwordLabel: '비밀번호',
    submit: '로그인',
    submitting: '확인 중…',
    errors: {
      missing: '아이디와 비밀번호를 입력하세요.',
      invalid: '아이디 또는 비밀번호가 맞지 않습니다.',
    },
  },
}

/**
 * 학년을 정하지 않은 대주제·세트의 학교급 표기(대표 결정 2026-09-26: 2022 개정 성취기준은 학년군 단위).
 * 프롬프트 쪽 같은 낱말은 lib/studio/level-map.ts SCHOOL_BANDS — tests/themes.test.ts 가 둘이 같은지 본다.
 */
const GRADE_BAND: Record<string, { school: string; short: string; band: string } | undefined> = {
  초: { school: '초등학교', short: '초등', band: '3~6학년' },
  중: { school: '중학교', short: '중등', band: '1~3학년군' },
  고: { school: '고등학교', short: '고등', band: '1~3학년' },
}
/** "중 1학년" / 학년 없음 → "중등 · 1~3학년군" (목록·머리말·카드) */
const levelGradeShort = (level: string, grade: number | null) => {
  if (grade != null) return `${level} ${grade}학년`
  const b = GRADE_BAND[level]
  return b ? `${b.short} · ${b.band}` : level
}
/** "중 1학년" / 학년 없음 → "중학교(1~3학년군)" (세트 표지·문제지) */
const levelGradeLong = (level: string, grade: number | null) => {
  if (grade != null) return `${level} ${grade}학년`
  const b = GRADE_BAND[level]
  return b ? `${b.school}(${b.band})` : level
}

export const app = {
  roleLabel: { admin: '본사 관리자', teacher: '원장님', student: '학생' },
  logout: '로그아웃',
  nav: {
    admin: [
      { href: '/admin', label: '대시보드' },
      { href: '/admin/academies', label: '가맹원 관리' },
      { href: '/admin/items', label: '문항 제작소' },
      { href: '/admin/inquiries', label: '가맹문의' },
      { href: '/admin/standards', label: '성취기준' },
    ],
    teacher: [
      { href: '/teacher', label: '홈' },
      { href: '/teacher/students', label: '학생 관리' },
      { href: '/teacher/items', label: '문항 찾기' },
      { href: '/teacher/assignments', label: '배정 현황' },
    ],
    student: [
      { href: '/student', label: '내 과제' },
    ],
  },
  dashboard: {
    admin: { title: '본사 대시보드', body: '가맹원·학생·채점 현황이 여기에 표시됩니다.' },
    teacher: {
      title: '원장님 홈',
      body: '학생 현황과 최근 결과가 여기에 표시됩니다.',
      stats: { pending: (n: number) => `검수 대기 ${n}건`, assignments: (n: number) => `진행 중 배정 ${n}개`, students: (n: number) => `학생 ${n}명` },
      links: { review: '검수하러 가기', assign: '문항 찾기', students: '학생 관리' },
    },
    student: { title: '내 과제', body: '아직 배정된 과제가 없어요.' },
  },
  adminInquiries: {
    title: '가맹문의 접수함',
    columns: { date: '접수', name: '이름', phone: '연락처', region: '지역', message: '내용', status: '상태' },
    statusLabel: { new: '신규', contacted: '연락함', done: '완료' } as const,
    empty: '아직 접수된 문의가 없습니다.',
  },
  adminAcademies: {
    listTitle: '가맹원 관리',
    columns: { code: '코드', name: '이름', region: '지역', teacherCount: '원장 수', studentCount: '학생 수' },
    newButton: '새 가맹원',
    form: {
      labels: { code: '원 코드', name: '원 이름', region: '지역', directorPhone: '원장 연락처' },
      submit: '등록',
    },
    teacherAccount: {
      heading: '원장 계정',
      formHeading: '원장 계정 발급',
      placeholders: { name: '원장님 이름', email: '원장님 이메일 (로그인 아이디)' },
      submit: '계정 발급',
      submitting: '발급 중…',
      issuedNotice: '아래 정보를 원장님께 전달하세요. 이 화면을 벗어나면 비밀번호를 다시 볼 수 없습니다.',
      labels: { id: '아이디:', password: '초기 비밀번호:' },
    },
    detailMeta: {
      studentCapacity: (n: number) => `학생 정원 ${n}`,
      monthlyGradingLimit: (n: number) => `월 채점 상한 ${n}건`,
    },
    errors: {
      codeInvalid: '원 코드는 영문 소문자·숫자 3~12자입니다.',
      nameRequired: '원 이름을 입력하세요.',
      codeTaken: '이미 있는 원 코드입니다.',
      teacherMissing: '이메일과 이름을 입력하세요.',
      invalidInput: '입력을 확인하세요.',
    },
  },
  adminStandards: {
    title: '성취기준 검증',
    filters: {
      levelLabel: '학교급',
      levelAll: '전체',
      subjectLabel: '과목',
      subjectAll: '전체',
      searchLabel: '검색',
      searchPlaceholder: '코드 또는 원문 검색',
      submit: '검색',
    },
    summary: (verified: number, total: number) => `검증 ${verified} / ${total}`,
    columns: { code: '코드', text: '원문', page: '쪽', status: '상태', action: '동작' },
    statusLabel: { verified: '검증됨', unverified: '미검증' },
    actions: { verify: '원문 확인', unverify: '해제' },
    empty: '조건에 맞는 성취기준이 없습니다.',
    pagination: { prev: '이전', next: '다음', pageOf: (page: number, total: number) => `${page} / ${total}` },
    crosscheck: {
      button: '원문 자동 대조',
      submitting: '대조 중…',
      result: (verifiedCount: number, mismatchedCount: number, unmatchedCount: number) =>
        `검증됨 ${verifiedCount}건 · 불일치 ${mismatchedCount}건 · 대조 불가 ${unmatchedCount}건`,
      mismatchHeading: '불일치 — 직접 확인 필요',
      mismatchColumns: { code: '코드', dbText: 'DB 원문', levelText: '성취수준 원문' },
      unmatchedNote: '성취수준 원문 자료가 없는 항목(고등학교 전 과목, 세계사 일부 등)은 자동 대조 대상이 아니며 미검증 상태로 남습니다.',
      error: '대조 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
  },
  studio: {
    gradeBand: GRADE_BAND,
    errors: {
      titleRequired: '대주제 제목을 입력하세요.',
      levelInvalid: '학교급을 선택하세요.',
      gradeInvalid: '학년을 확인하세요. (초 1~6, 중·고 1~3, 또는 학년 지정 안 함)',
      subjectsRequired: '과목을 1개 이상 선택하세요.',
      subjectInvalid: '알 수 없는 과목입니다.',
      subjectNotInTheme: '대주제에 포함되지 않은 과목입니다.',
      subjectDuplicate: '이미 세트가 만들어진 과목입니다.',
      standardCountInvalid: '성취기준은 2~6개 선택하세요.',
      standardLevelMismatch: '대주제와 학교급이 다른 성취기준이 있습니다.',
      standardSubjectMismatch: '대주제와 과목이 다른 성취기준이 있습니다.',
      standardUnverified: (codes: string[]) => `원문 미검증 성취기준: ${codes.join(', ')}`,
      invalidStandards: '선택한 성취기준을 확인할 수 없습니다. 다시 선택해 주세요.',
      materialsInvalid: '공유 자료 형식을 확인하세요.',
      themeNotFound: '대주제를 찾을 수 없습니다.',
      saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
    themes: {
      title: '대주제 목록',
      newButton: '새 대주제',
      columns: {
        title: '제목',
        level: '학교급/학년',
        subjects: '과목',
        setCount: '세트 수',
        publishedCount: '게시 수',
        action: '동작',
      },
      open: '열기',
      empty: '아직 만들어진 대주제가 없습니다.',
    },
    newTheme: {
      title: '새 대주제',
      labels: { title: '제목', level: '학교급', grade: '학년(선택)', subjects: '과목' },
      gradeNone: '학년 지정 안 함(학년군 전체)',
      gradeOption: (grade: number) => `${grade}학년`,
      gradeHelp: '2022 개정 성취기준은 학년군 단위입니다. 학년을 정하지 않으면 중학교는 1~3학년군, 초등학교는 3~6학년 수준으로 만듭니다. 초등은 1~6학년, 중등은 1~3학년 중에서 고를 수 있습니다.',
      submit: '만들기',
      submitting: '만드는 중…',
    },
    theme: {
      backToList: '← 목록으로',
      meta: (level: string, grade: number | null) => levelGradeShort(level, grade),
      gradeEdit: {
        label: '학년 바꾸기',
        help: '학년을 정하지 않으면 AI가 학교급 학년군 전체(중학교 1~3학년군, 초등학교 3~6학년) 수준으로 만듭니다. 바꾼 학년은 이 대주제의 세트에도 적용됩니다 — 이미 게시한 판은 다시 게시해야 표지가 바뀝니다.',
        submit: '바꾸기',
        submitting: '바꾸는 중…',
        saved: '학년을 바꿨습니다.',
      },
      addSubjects: {
        heading: '과목 추가',
        help: '대주제를 만들 때 고르지 않은 과목을 나중에 추가합니다.',
        submit: '추가',
        submitting: '추가하는 중…',
        saved: '과목을 추가했습니다.',
        nothingToAdd: '추가할 수 있는 과목이 없습니다.',
        remove: {
          help: '세트를 아직 만들지 않은 과목은 [빼기]로 대주제에서 뺄 수 있습니다.',
          button: '빼기',
          removing: '빼는 중…',
          removed: '과목을 뺐습니다.',
          hasSet: '이미 세트가 만들어진 과목은 뺄 수 없습니다.',
          lastSubject: '대주제에는 과목이 하나 이상 있어야 합니다.',
        },
      },
    },
    // 대주제 소개(0단계)는 검토 관문이 없다(2026-09-24 오너 결정) — AI 초안을 받아 고치거나 직접 써서 저장하면 바로 확정된다.
    intro: {
      heading: '대주제 소개',
      help: '대주제를 한눈에 소개하는 글과 과목별 접근 한 줄입니다. AI 초안을 받아 고치거나 직접 쓰고 저장하세요. 이 글은 이후 단계의 배경 설명과 세트 첫 장에 쓰입니다.',
      mockBadge: '가짜 응답',
      busy: '처리 중…',
      introLabel: '소개 문구 (3~4문장)',
      ideaLabel: (subject: string) => `${subject} 아이디어`,
      draftButton: 'AI 초안 받기',
      save: '저장',
      saved: '저장했습니다.',
      errors: {
        generic: '요청 처리 중 오류가 났습니다.',
        introTooShort: '소개 문구를 20자 이상 써 주세요.',
        ideaTooShort: '한 줄 아이디어를 5자 이상 써 주세요.',
      },
    },
    materials: {
      heading: '공유 자료',
      description: '이 대주제의 모든 세트가 공유하는 자료입니다. 2A 스키마(JSON)를 그대로 붙여넣으세요.',
      submit: '저장',
      submitting: '저장 중…',
      saved: '저장했습니다.',
    },
    charts: {
      count: '도수',
      relative: '상대도수',
      value: '값',
    },
    sets: {
      heading: '세트 목록',
      newSetHeading: '세트 만들기',
      statusLabel: { draft: '초안', review: '검토중', published: '게시됨', retired: '내림' },
      progress: (n: number) => `${n}/5 확정`,
      open: '열기',
      empty: '아직 만들어진 세트가 없습니다.',
    },
    picker: {
      subjectLabel: '과목',
      subjectPlaceholder: '과목을 선택하세요',
      noSubjectsAvailable: '모든 과목에 이미 세트가 있습니다.',
      uncategorized: '미분류',
      searchPlaceholder: '코드 또는 원문 검색',
      selectedCount: (n: number) => `${n}개 선택 (2~6개)`,
      verified: '검증됨',
      unverified: '미검증',
      unverifiedWarning: (codes: string[]) => `다음 성취기준은 원문 미검증입니다: ${codes.join(', ')}`,
      submit: '세트 만들기',
      submitting: '만드는 중…',
      empty: '해당 과목의 성취기준이 없습니다.',
    },
    wizard: {
      backToTheme: '← 세트 목록으로',
      versionLabel: (v: number) => `버전 ${v}`,
      stageNames: { 2: '재구성·목표·핵심질문', 3: '차시 설계', 4: '자료', 5: '평가', 6: '교사용 지침서', 7: '안내장 틀' } as Record<number, string>,
      // 대표 결정 2026-09-26: [생성] → 읽기 → [확인]. 검토는 참고(선택)이고 진행을 막지 않는다.
      stateLabel: { idle: '준비 전', generated: '생성됨', reviewed: 'AI 의견 받음', accepted: '확인됨', failed: '실패' },
      mockBadge: '가짜 응답',
      editedBadge: '편집됨',
      attemptLabel: (n: number) => `시도 ${n}`,
      actions: {
        generate: '생성',
        review: 'AI 검토 의견 보기',
        accept: '확인',
        runDefaults: '기본값으로 진행',
        editJson: 'JSON 편집',
        cancelEdit: '취소',
        save: '저장',
      },
      busy: '처리 중…',
      empty: '아직 생성된 결과가 없습니다. [생성]을 눌러 시작하세요.',
      // 생성 직후 자동으로 도는 형식·원문 검사의 지적 — 참고용 메모(막지 않는다)
      notesHeading: '자동 검사 메모 (참고)',
      notesNone: '자동 검사에서 짚은 점이 없습니다.',
      // [AI 검토 의견 보기]를 눌렀을 때만 나온다 — 참고용
      aiReviewHeading: 'AI 검토 의견 (참고)',
      aiReviewNone: 'AI가 짚은 점이 없습니다.',
      errorPrefix: '오류: ',
      // AI 출력이 형식 검사(zod)를 통과하지 못했을 때 — 원인 문구(claude.ts)를 그대로 보여 주지 않고 이 안내를 앞에 두고, 원문은 작게 아래에 둔다
      parseErrorHeading: 'AI 출력이 형식 검사를 통과하지 못했습니다 — [생성]을 다시 누르세요.',
      prevStageHint: '이전 단계를 먼저 [확인]해야 진행할 수 있습니다.',
      keyQuestion: {
        heading: '핵심질문 선택',
        empty: '2단계를 확인하면 후보가 표시됩니다.',
        select: '선택',
        current: (q: string) => `현재 핵심질문: ${q}`,
        saved: '핵심질문을 저장했습니다.',
      },
      stage2: {
        reconstructionLabel: '재구성 문장',
        goalsLabel: '학습 목표',
        goal: (text: string, axis: string) => `${text} (${axis})`,
        candidatesLabel: '핵심질문 후보',
      },
      stage3: {
        columns: {
          no: '차시',
          standards: '담당 성취기준',
          keyQuestion: '차시 핵심질문',
          quizCount: '퀴즈 수',
          assessment: '평가 배치',
          mergeable: '병합 가능',
        },
        noAssessment: '-',
      },
      stage4: {
        idLabel: '자료',
        kindLabel: '종류',
        previewHeading: '표 미리보기(상위 5행)',
        bodyPreviewHeading: '본문 미리보기',
        imagesCount: (n: number) => `이미지 ${n}장`,
      },
      // 5단계 요약(Stage5Summary.tsx): 문항 카드(조건·채점표·예시답안 전부) + 두 문항 공통 채점 기준표(등급표·피드백 틀)
      stage5: {
        itemsHeading: '문항',
        itemLabel: (no: number) => `${no}번`,
        pointsLabel: (n: number) => `${n}점`,
        lessonLabel: (no: number) => `${no}차시`,
        answerMode: { screen: '화면 입력', paper: '종이 답안(사진 제출)' } as Record<string, string>,
        situationLabel: '과제 상황',
        situation: (role: string, audience: string, purpose: string, product: string) => `${role} → ${audience} · ${purpose} · ${product}`,
        materialsLabel: '사용 자료',
        materialRef: (id: string) => `자료 ${id}`,
        conditionsHeading: '조건',
        conditionNo: (no: number) => `조건 ${no}.`,
        noConditions: (kind: string) => (kind === '서술형' ? '조건 없음(서술형)' : '조건 없음'),
        lengthLabel: '분량',
        formatLabel: '형식',
        overflowLabel: '초과 응답',
        rubricHeading: '채점표',
        criterionColumn: '평가 요소',
        pointColumn: (n: number) => `${n}점`,
        criterionLabel: (name: string, max: number) => `${name} (0~${max}점)`,
        conditionRefs: (nos: number[]) => (nos.length ? `조건 ${nos.join('·')}` : ''),
        noStep: '—',
        exampleLabel: '예',
        holisticHeading: '총체적 기준',
        levels: { 상: '상', 중: '중', 하: '하' },
        notesHeading: '채점 시 유의점',
        exemplarsHeading: '예시답안',
        exemplarCount: (itemNo: number, n: number) => `${itemNo}번 문항 예시답안 ${n}개`,
        exemplarLabel: (level: string | null, points: number) => `${level ?? ''} ${points}점`.trim(),
        exemplarScores: (scores: number[]) => `요소별 ${scores.join('·')}`,
        rationaleLabel: '채점자 의견',
        levelMapHeading: 'A~E 예상 점수',
        referencesHeading: '참고한 예시',
        commonHeading: '채점 기준표(공통)',
        commonNote: '두 문항 점수의 합으로 등급을 정합니다. 학생에게는 보이지 않습니다.',
        boundariesHeading: '등급표',
        boundaryColumns: { grade: '등급', range: '점수 범위', band: '수준', levelRef: '수준 참조' },
        boundaryRange: (min: number, max: number) => `${min}~${max}점`,
        feedbackHeading: '피드백 틀',
      },
      stage6: {
        termsCount: (n: number) => `용어 ${n}개`,
        notesCount: (n: number) => `차시별 메모 ${n}개`,
      },
      stage7: {
        summary: (lessons: number, essays: number) => `차시 ${lessons}개 · 서·논술형 차시 문구 ${essays}개`,
      },
      errors: {
        invalidJson: 'JSON 형식을 확인하세요.',
        invalidShape: (msg: string) => `형식이 올바르지 않습니다: ${msg}`,
        keyQuestionInvalid: '핵심질문 후보 중에서 선택하세요. (2단계를 먼저 확인해야 합니다)',
        prevNotAccepted: '이전 단계를 먼저 확인해야 이 단계를 수정할 수 있습니다.',
        tooFewStandards: '세트에 성취기준이 2개 이상 연결되어야 합니다.',
        saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        generic: '요청 처리 중 오류가 났습니다.',
        autoStopped: '생성이 실패해 자동 진행을 멈췄습니다. 멈춘 단계에서 [생성]을 다시 누르세요.',
      },
    },
    attachments: {
      heading: '이미지 첨부',
      description: '자료·차시에 이미지를 첨부합니다. (PNG·JPG·WEBP, 5MB 이하)',
      targetLabel: '첨부 대상',
      materialLabel: (id: string) => `자료 ${id}`,
      lessonLabel: (no: number) => `${no}차시`,
      noTargets: '자료 또는 차시를 먼저 생성해야 첨부할 수 있습니다.',
      fileLabel: '이미지 파일',
      upload: '업로드',
      uploading: '업로드 중…',
      empty: '첨부된 이미지가 없습니다.',
      delete: '삭제',
      thumbnailAlt: (target: string, n: number) => `${target} 첨부 이미지 ${n}`,
      errors: {
        invalidTarget: '첨부 대상을 확인하세요.',
        invalidUrl: '이미지 주소를 확인할 수 없습니다.',
        itemNotFound: '해당 자료·차시를 찾을 수 없습니다.',
        invalidShape: '이미지 목록 형식이 올바르지 않습니다.',
        saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        uploadFailed: '업로드 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        fileTooLarge: '파일 크기는 5MB 이하만 가능합니다.',
        invalidType: 'PNG·JPG·WEBP 파일만 업로드할 수 있습니다.',
      },
    },
    publish: {
      tabs: { wizard: '제작', preview: '미리보기' },
      heading: '게시',
      currentStatusLabel: '현재 상태',
      currentVersionLabel: (v: number) => `현재 버전 ${v}`,
      nextVersionLabel: (v: number) => `다음 버전 ${v}`,
      button: '게시하기',
      busy: '게시 중…',
      success: (v: number) => `버전 ${v}로 게시했습니다.`,
      blockersHeading: '아직 게시할 수 없습니다',
      blockers: {
        stageNotAccepted: (stage: number) => `${stage}단계를 아직 [확인]하지 않았습니다.`,
        unverifiedStandard: (code: string) => `성취기준 ${code}이(가) 원문 검증되지 않았습니다.`,
        noKeyQuestion: '핵심질문이 아직 선택되지 않았습니다.',
        quizChoice: (n: number) => `${n}차시 퀴즈에 선택지가 남아 있습니다 — 3단계를 다시 생성하세요.`,
        unknown: '게시할 수 없습니다. 단계·성취기준·핵심질문을 확인하세요.',
      },
      errors: {
        forbidden: '게시 권한이 없습니다.',
        saveFailed: '게시 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
      },
    },
  },
  packageView: {
    cover: {
      versionLabel: (v: number) => `버전 ${v}`,
      publishedAtLabel: '게시일',
      meta: (level: string, grade: number | null, subject: string) => `${levelGradeLong(level, grade)} · ${subject}`,
    },
    intro: '대주제 소개',
    standardsHeading: '성취기준',
    levelsHeading: '성취수준(A~E)',
    levelsToggle: '성취수준 보기',
    reconstructionHeading: '재구성',
    reconstructionTable: { columns: { code: '코드', original: '원문', type: '유형', reconstructed: '재구조화', reason: '이유', elements: '학습요소' } },
    learningGoalsHeading: '학습 목표',
    learningGoals: { axisLabel: (axis: string) => axis },
    keyQuestionHeading: '핵심 질문',
    unitPlanHeading: '평가 계획',
    unitPlan: {
      formativeLabel: '형성평가',
      placementLabel: '서·논술형 배치',
      rubricNoteLabel: '종합 도달 모습',
      placement: (kind: string, no: number) => `${kind} → ${no}차시`,
      lessonMapLabel: '차시 구성',
      lessonMapItem: (no: number, topic: string) => `${no}차시 ${topic}`,
    },
    answersToggle: '정답·채점 자료 펼치기',
    materialsHeading: '자료',
    // 관리자 미리보기만: 게시 판에서 뺀 자료(어느 문항·차시도 쓰지 않음, 대표 2026-09-26 — 세트는 실제로 쓰는 자료만 싣는다)
    materialsOmitted: (ids: string[]) => `게시 판에서 빠지는 자료: ${ids.map((id) => `자료 ${id}`).join(', ')} — 어느 문항·차시도 쓰지 않습니다.`,
    materials: {
      idLabel: '자료',
      imagesAlt: (title: string, n: number) => `${title} 첨부 이미지 ${n}`,
      sourceLabel: { 자작: '자작', 공개: '공개 자료' },
      aiBadge: 'AI 보조 · 확인 필요',
      roleLabel: { raw: '원자료', context: '배경' },
    },
    lessonsHeading: '차시',
    lessons: {
      columns: { no: '차시', standards: '담당 성취기준', keyQuestion: '차시 핵심질문', goal: '목표', assessment: '평가 배치', mergeable: '병합 가능' },
      noAssessment: '-',
      flow: { intro: '도입', main: '전개', wrapup: '정리' },
      materialsLabel: '사용 자료',
      quizHeading: '퀴즈',
      quiz: {
        typeLabel: { choice: '선택형', short: '단답형' },
        answerLabel: '정답',
        explanationLabel: '해설',
        answersHidden: '정답·해설은 원장님 화면에서만 표시됩니다.',
      },
      imagesAlt: (no: number, n: number) => `${no}차시 첨부 이미지 ${n}`,
      topicLabel: '주제',
      timeLabel: (i: number, m: number, w: number) => `도입 ${i}분 · 전개 ${m}분 · 정리 ${w}분`,
      stepLabel: (label: string, minutes: number) => `${label} (${minutes}분)`,
      scriptHeading: '발문 대본',
      scriptExpected: '예상 답',
      scriptStuck: '막힐 때',
      needsLabel: '준비물',
      cautionHeading: '지도상 유의점',
      worksheetHeading: '활동지',
      worksheetTier: (tier: string, ref: string) => `${tier}(${ref})`,
      worksheetExpected: '기대 답',
      selfCheckHeading: '자기평가',
      mergeNoteLabel: '병합 시 생략',
      mergeableLabel: (no: number) => `${no}차시와 병합 가능`,
      assessmentSessionBadge: '단원 평가',
      // 분은 세트 구조(lib/studio/assessment-structure.ts ASSESSMENT_SESSION)에서 넘겨받는다
      assessmentSessionNote: (shortMin: number, essayMin: number) => `마지막 교수 차시 뒤에 서술형(${shortMin}분)과 논술형(${essayMin}분)을 함께 보는 평가 차시입니다. 퀴즈·활동지는 없고, 문항은 아래 평가 문항 카드에 있습니다.`,
    },
    teacherGuideHeading: '교사용 지침서',
    teacherGuide: {
      generalHeading: '전체 안내',
      materialsLabel: '준비물',
      scheduleLabel: '차시 운영 메모',
      purposeLabel: '수업 의도',
      glossaryHeading: '용어 설명',
      perLessonHeading: '차시별 유의점',
      lessonLabel: (no: number) => `${no}차시`,
      mergeHeading: '병합 안내',
      mergeLabel: (a: number, b: number) => `${a}·${b}차시 병합`,
      mergeSkip: '생략 활동',
      mergeTime: (i: number, m: number, w: number) => `120분: 도입 ${i}분 · 전개 ${m}분 · 정리 ${w}분`,
      gradingHeading: '검수 요령',
      commonErrors: '흔한 오답',
      commonErrorItem: (itemNo: number) => `문항 ${itemNo}`,
      reviewTips: '검수 팁',
      retryLabel: '재도전 안내',
    },
    assessmentHeading: '평가 문항',
    assessment: {
      kindLabel: { 서술형: '서술형', 논술형: '논술형' },
      lessonLabel: (no: number) => `${no}차시 연계`,
      pointsLabel: (n: number) => `${n}점`,
      conditions: {
        lengthLabel: '분량', requiredLabel: '필수 포함', formatLabel: '형식',
        heading: '조건',
        itemNo: (no: number) => `조건 ${no}.`,
        answerMode: { screen: '화면 입력', paper: '종이 답안(사진 제출)' },
        overflowLabel: '초과 응답',
        pointsLabel: (p: number) => `${p}점`,
      },
      elementsLabel: '평가 요소',
      situationLabel: '과제 상황',
      situation: (role: string, audience: string, purpose: string, product: string) => `${role} → ${audience} · ${purpose} · ${product}`,
      materialsLabel: '사용 자료',
      notesHeading: '채점 시 유의점',
      exemplarsHeading: '예시답안',
      exemplarLabel: (level: string | null, points: number) => `${level ?? ''} ${points}점`.trim(),
      exemplarScores: (scores: number[]) => `요소별 ${scores.join('·')}`,
      rationaleLabel: '채점자 의견',
      levelMapHeading: 'A~E 예상 점수',
      minCompetencyLabel: '최소 능력',
      referencesHeading: '참고한 공개 자료',
    },
    rubricHeading: '채점표',
    rubric: {
      criteriaLabel: '평가 요소',
      criterionLabel: (name: string, max: number) => `${name} (0~${max}점)`,
      axisLabel: '축',
      conditionsLabel: (nos: number[]) => (nos.length ? `조건 ${nos.join('·')}` : ''),
      pointLabel: (n: number) => `${n}점`,
      exampleLabel: '예',
      holisticHeading: '총체적 기준',
    },
    shortRubric: { pointsLabel: '점수', expectationLabel: '기대 응답', exampleLabel: '예시' },
    extendedRubric: { criteriaLabel: '평가 요소', bandLabel: (n: number) => `${n}점` },
    gradingCriteriaHeading: '채점 기준',
    gradingCriteriaNote: '두 문항 점수의 합으로 등급을 정합니다. 문항별 채점표는 각 문항 카드에 있습니다.',
    gradeBoundariesHeading: '등급 경계표',
    gradeBoundaries: { gradeLabel: '등급', rangeLabel: '점수 범위', bandLabel: '수준', levelRefLabel: '수준 참조' },
    exemplarsHeading: '예시답안',
    exemplars: { levelLabel: { 상: '상', 중: '중', 하: '하' }, scoresLabel: '요소별 점수', totalLabel: (n: number) => `총점 ${n}`, gradeLabel: (n: number) => `${n}등급` },
    feedbackTemplatesHeading: '피드백 틀',
    feedbackLevels: { 상: '상', 중: '중', 하: '하' },
    noticePlanHeading: '안내장 틀',
    noticePlan: { lessonLabel: (n: number) => `${n}차시`, summary: '학습 요약', preview: '다음 차시', home: '가정 학습', quizNotes: '퀴즈 오답 코멘트', phrases: '요소별 문구', good: '잘한 점', improve: '보완' },
    generatedWithHeading: '생성 모델',
    empty: '아직 내용이 없습니다.',
    // 문제지 인쇄(간단판): 표지·자료·문항·답란만 종이에 남긴다(app/globals.css 의 html.print-questions)
    print: {
      button: '문제지 인쇄',
      paperBox: '종이 답안 — 이 칸에 직접 쓰거나 그리세요.',
      studentLine: { name: '이름', date: '날짜' },
    },
  },
  teacherItems: {
    title: '문항 찾기',
    filters: {
      levelLabel: '학교급',
      levelAll: '전체',
      subjectLabel: '과목',
      subjectAll: '전체',
      submit: '검색',
    },
    card: {
      versionLabel: (v: number) => `버전 ${v}`,
      meta: (level: string, grade: number | null) => levelGradeShort(level, grade),
      open: '열기',
    },
    empty: '아직 게시된 문항이 없습니다.',
    detail: {
      backToList: '← 목록으로',
      notFoundTitle: '게시된 문항을 찾을 수 없습니다.',
    },
  },
  classroom: {
    print: '인쇄',
    students: {
      title: '학생 관리',
      columns: { name: '이름', grade: '학년', loginId: '아이디', assignments: '배정', actions: '동작' },
      empty: '아직 등록된 학생이 없습니다. 오른쪽에서 첫 학생을 추가하세요.',
      form: {
        heading: '학생 추가',
        nameLabel: '이름',
        levelLabel: '학교급',
        gradeLabel: '학년',
        submit: '추가',
        submitting: '만드는 중…',
      },
      issued: {
        heading: '계정이 만들어졌습니다',
        body: '아래 아이디와 초기 비밀번호는 지금 한 번만 보입니다. 인쇄하거나 복사해 학생에게 전해 주세요.',
        loginId: '아이디',
        password: '초기 비밀번호',
        copy: '복사',
        copied: '복사했습니다',
        close: '닫기',
      },
      reset: { button: '비밀번호 초기화', confirm: '새 비밀번호를 만들까요? 학생은 이전 비밀번호로 로그인할 수 없게 됩니다.', done: '새 비밀번호' },
      errors: {
        nameMissing: '이름을 입력하세요.',
        levelInvalid: '학교급을 고르세요.',
        gradeInvalid: '학년은 1~6 사이 숫자여야 합니다.',
        createFailed: '계정을 만들지 못했습니다. 잠시 후 다시 시도하세요.',
        forbidden: '권한이 없습니다.',
      },
    },
    assign: {
      button: '배정하기',
      newTitle: '배정하기',
      students: '학생 선택',
      selectAll: '전체 선택',
      alreadyAssigned: '이미 배정됨',
      gradeMismatch: (grade: number) => `세트 학년(${grade}학년)과 다릅니다`,
      dueLabel: '마감일',
      retryLabel: '재도전 허용',
      openLabel: '처음 열 차시 수',
      submit: '배정',
      submitting: '배정 중…',
      listTitle: '배정 현황',
      listEmpty: '아직 배정한 세트가 없습니다. 문항 찾기에서 세트를 열고 [배정하기]를 누르세요.',
      card: {
        students: (n: number) => `학생 ${n}명`,
        open: (n: number) => `${n}차시까지 열림`,
        pending: (n: number) => `검수 대기 ${n}건`,
        due: (d: string) => `마감 ${d}`,
        openButton: '열기',
      },
      detail: {
        backToList: '← 배정 현황으로',
        openLessons: '차시 열기',
        openTo: (n: number) => `${n}차시까지 열기`,
        applyAll: '반 전체에 적용',
        saved: '저장했습니다',
      },
      errors: {
        noStudents: '학생을 한 명 이상 고르세요.',
        setNotFound: '게시된 세트를 찾을 수 없습니다.',
        saveFailed: '저장하지 못했습니다. 다시 시도하세요.',
        invalidLessons: '차시 수가 올바르지 않습니다.',
      },
    },
    student: {
      listTitle: '내 과제',
      empty: '아직 배정된 과제가 없어요.',
      card: {
        due: (d: string) => `마감 ${d}`,
        progress: (open: number, quizDone: number, quizTotal: number, answerDone: number, answerTotal: number) =>
          `${open}차시까지 열림 · 퀴즈 ${quizDone}/${quizTotal} · 답안 ${answerDone}/${answerTotal}`,
        todo: '할 일 있음', reviewing: '선생님 확인 중', done: '결과 나옴', open: '열기',
      },
      lessonTab: (n: number) => `${n}차시`,
      // 마지막 교수 차시 뒤 단원 평가 차시(서술형 + 논술형, 대표 2026-09-26) 탭
      assessmentTab: (n: number) => `${n}차시 · 단원 평가`,
      assessmentIntro: (shortMin: number, essayMin: number) => `이 시간에는 서술형 문항(${shortMin}분)과 논술형 문항(${essayMin}분)에 차례로 답해요. 자료를 보면서 써도 돼요.`,
      locked: '아직 열리지 않았어요',
      keyQuestion: '이 시간의 질문',
      materials: '자료',
      quiz: {
        heading: '마무리 퀴즈',
        submit: '제출',
        submitted: (correct: number, total: number) => `${total}문항 중 ${correct}개 정답`,
        answerLabel: '정답', explanationLabel: '해설', yourAnswer: '내 답',
        shortPlaceholder: '답을 쓰세요',
      },
      paperAnswer: '이 문항은 표·그래프를 직접 작성하는 문항이에요. 종이에 풀어 선생님께 내세요. 선생님이 사진으로 올려 주시면 결과가 여기에 보여요.',
      conditionItem: (no: number) => `조건 ${no}`,
      answer: {
        heading: (label: string, points: number) => `${label} (${points}점)`,
        stem: '문항',
        conditions: '작성 조건 (아래 조건을 모두 지켜 쓰세요)',
        // 조건이 없는 문항(서술형, C-32)은 조건 머리글 없이 분량·형식만 보인다
        lengthFormat: '분량·형식',
        conditionLength: '분량:',
        conditionFormat: '형식:',
        chars: (n: number) => `${n}자`,
        saving: '저장 중…', saved: '임시저장됨',
        submit: '제출', confirm: '제출하면 고칠 수 없어요. 제출할까요?',
        submitted: '제출했어요. 선생님이 확인 중이에요.',
        tooShort: '조금 더 써 보세요. 조건을 다시 읽어 보세요. (50자 이상)',
        placeholder: '여기에 답안을 쓰세요',
      },
      errors: { notOpen: '아직 열리지 않은 차시예요.', alreadySubmitted: '이미 제출했어요.', saveFailed: '저장하지 못했어요. 다시 시도해 주세요.', paperOnly: '종이 답안 문항은 선생님이 사진으로 올려 주세요.' },
      result: {
        heading: (label: string) => `${label} 결과`,
        score: (s: number, max: number) => `${s}/${max}점`,
        criteria: '요소별 점수', evidence: '근거 문장',
        strengths: '잘한 점', improvements: '보완할 점', comment: '선생님 한마디',
        overall: (total: number, max: number, grade: number, band: string) => `종합 ${total}/${max}점 · ${grade}등급 · ${band}`,
        retry: '다시 써 보기',
        retryHint: '피드백을 보고 같은 문항에 한 번 더 답을 쓸 수 있어요. 첫 번째 답과 점수는 그대로 남아요.',
        attempt: (n: number) => `${n}회차`,
        firstAttempt: '1회차 답안과 피드백 보기',
      },
    },
    review: {
      quizHeading: '퀴즈 현황',
      quizRate: (pct: number) => `정답률 ${pct}%`,
      overrideCorrect: '정답 처리', overrideWrong: '오답 처리', noResponse: '—',
      answersHeading: '답안·검수',
      status: { none: '미제출', pending: '채점 중', drafted: '검수 대기', confirmed: '공개됨', failed: '실패', rejected: '다시 쓰기 요청', retry: '재도전 중' },
      attempt: (n: number) => `${n}회차`,
      studentAnswer: '학생 답안',
      aiDraft: 'AI 초안', finalLabel: '확정본',
      mock: '가짜 응답',
      criteria: '요소별 점수', evidence: '근거', score: '문항 점수',
      strengths: '잘한 점', improvements: '보완할 점', addLine: '문장 추가', remove: '지우기',
      comment: '원장 코멘트', adjustNote: '조정 이유(선택)',
      confirmAsIs: '그대로 확정', confirmEdited: '수정하여 확정', regrade: 'AI 다시 채점', requestRegrade: '재채점 요청(본사)', reopen: '다시 고치기',
      confirmedAt: (at: string) => `공개됨 · ${at}`,
      overall: (total: number, max: number, grade: number, band: string) => `종합 ${total}/${max}점 · ${grade}등급 · ${band}`,
      overallPending: '서·논술형 문항이 모두 확정되면 종합 점수가 나옵니다.',
      compare: (a1: number, a2: number) => `1회차 ${a1}점 → 2회차 ${a2}점`,
      errors: { saveFailed: '저장하지 못했습니다.', notDrafted: '검수 대기 상태가 아닙니다.', badScore: '점수가 범위를 벗어났습니다.' },
    },
    // 학생별 차시 안내장(v2 T8) — 원장 화면에서 초안 → 확정 → 인쇄. 학교생활기록부가 아니다.
    notice: {
      title: (name: string, no: number) => `${name} · ${no}차시 안내장`,
      docTitle: '차시별 피드백 안내장',
      back: '← 배정 상세로',
      cardHeading: '안내장',
      cardLink: (no: number) => `${no}차시`,
      draft: '안내장 초안 만들기', redraft: '다시 만들기', drafting: '만드는 중…',
      redraftConfirm: '초안을 다시 만들면 고친 문장이 새 초안으로 바뀝니다(참여 관찰·원장 한마디는 그대로 둡니다). 다시 만들까요?',
      confirm: '확정', reconfirm: '고쳐서 다시 확정', confirming: '저장 중…', confirmed: '확정했습니다.',
      print: '인쇄', printHint: '확정한 안내장만 인쇄할 수 있습니다.',
      status: { draft: '초안(확정 전)', confirmed: '확정' },
      confirmedAt: (at: string) => `확정 ${at}`,
      student: '학생', date: '수업일',
      sections: { context: '이번 차시 학습 내용', participation: '참여·퀴즈 결과', essay: '서·논술형 결과', next: '다음 차시·가정 학습', director: '원장 한마디' },
      keyQuestion: '핵심 질문', goal: '학습 목표', summary: '오늘 배운 것',
      quizResult: (c: number, t: number) => `${t}문항 중 ${c}개 정답`,
      quizCols: { no: '번호', q: '문항', result: '결과', note: '코멘트' },
      quizCorrect: '정답', quizWrong: '다시 보기',
      score: (s: number, t: number, band: string) => `${s}/${t}점 · ${band}`,
      criteriaCols: { name: '평가 요소', score: '점수', good: '잘한 점', improve: '보완할 점' },
      criterionScore: (s: number, m: number) => `${s}/${m}`,
      retry: (b: number, a: number) => `1회차 ${b}점에서 출발 → 재도전 ${a}점`,
      preview: '다음 시간', homeStudy: '가정 학습 제안',
      directorCommentLabel: '참여 관찰(원장 작성)', directorMessageLabel: '원장 한마디',
      edit: {
        heading: '문장 고치기',
        hint: '점수·정오는 확정 채점에서 그대로 옵니다. 문장만 고칠 수 있습니다. 참여 관찰·원장 한마디는 비워 두면 안내장에서 빠집니다.',
        topicSummary: '학습 요약', quizNote: (n: number) => `퀴즈 ${n} 코멘트`,
        good: (name: string) => `${name} · 잘한 점`, improve: (name: string) => `${name} · 보완할 점`,
        improvementFor: (kind: string) => `${kind} 재도전 코멘트`, preview: '다음 차시 예고', homeStudy: '가정 학습 제안',
        directorComment: '참여 관찰(구체 행동과 함께)', directorMessage: '원장 한마디',
        maxChars: (n: number, max: number) => `${n}/${max}자`,
      },
      lintHeading: '문장 규칙 확인(고친 뒤 다시 눌러 주세요)',
      noNotice: '아직 안내장이 없습니다. 확정된 채점과 퀴즈 결과로 초안을 만듭니다.',
      errors: {
        notFound: '배정을 찾을 수 없습니다.',
        noPlan: '이 세트에는 안내장 틀이 없습니다(v2 게시본만 지원).',
        badLesson: '차시 번호가 올바르지 않습니다.',
        invalid: '안내장 모양이 올바르지 않습니다.',
        lint: '문장 규칙 위반이 있어 저장하지 않았습니다.',
        stale: '초안을 만든 뒤 채점이나 퀴즈 결과가 바뀌었습니다. [다시 만들기]를 눌러 주세요.',
        noDraft: '먼저 초안을 만들어 주세요.',
        aiFailed: 'AI 초안을 만들지 못했습니다. 잠시 후 다시 시도해 주세요.',
        saveFailed: '저장에 실패했습니다.',
      },
    },
  },
}

export const email = {
  inquiry: {
    // Resend에서 davinci-lab.kr 도메인 인증 후 lib/email/config.ts 의 주소를 교체할 때 이 표시 이름을 쓴다.
    fromName: '다빈치스쿨',
    subject: (region: string, name: string) => `[가맹문의] ${region} ${name}`,
    labels: { name: '이름', phone: '연락처', region: '지역' },
  },
}

export const pages = {
  comingSoon: {
    eyebrow: 'COMING SOON',
    title: (name: string) => `${name}은(는) 준비 중입니다`,
    body: '곧 자세한 안내를 드리겠습니다.',
    back: '메인으로',
  },
  program: {
    cta: '이 수업으로 가맹 문의',
  },
  franchise: {
    title: '다빈치스쿨 가맹 안내',
    intro: '본사가 교재·문항·교사용 지침서·AI 채점 시스템을 제공합니다. 원장님은 학생과 수업에 집중하세요.',
    formTitle: '문의 남기기',
    fields: {
      name: { label: '이름' },
      phone: { label: '연락처', placeholder: '010-0000-0000' },
      region: { label: '지역', placeholder: '예: 경기 성남' },
      message: { label: '문의 내용' },
    },
    submit: '문의 보내기',
    submitting: '보내는 중…',
    success: {
      title: '문의가 접수되었습니다',
      body: '본사에서 1~2일 안에 연락드리겠습니다.',
    },
    errors: {
      name: '이름을 입력하세요.',
      phone: '연락처를 확인하세요.',
      region: '지역을 입력하세요.',
      generic: '입력을 확인하세요.',
      submitFailed: '접수 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
  },
}
