export type ProgramSlug = 'inquiry' | 'essay' | 'consulting' | 'lab'

export const site = {
  name: '다빈치스쿨',
  tagline: '스스로 묻고, 탐구하고, 글로 증명하는 아이들',
  intro:
    '다빈치스쿨은 5년간 40권의 탐구보고서 교재로 검증된 수업을 전국 가맹원에 공급하는 교육 본사입니다. 이제 서논술형 수업과 AI 피드백으로 아이의 생각을 글로 완성합니다.',
  metaDescription: '탐구보고서와 서논술형 수업, 전국 가맹원 네트워크 다빈치스쿨',
  stats: [
    { label: '전국 가맹원', value: '40+' },
    { label: '탐구보고서 교재', value: '40권' },
    { label: '누적 수업 기간', value: '5년' },
  ],
  programs: [
    { slug: 'inquiry', name: '탐구보고서', short: '질문에서 보고서까지, 5년 검증된 탐구 수업', status: 'open', accent: 'mint' },
    { slug: 'essay', name: '서논술형 수업', short: '성취기준 기반 문항과 AI 채점·피드백', status: 'open', accent: 'lemon' },
    { slug: 'consulting', name: '대입 컨설팅', short: '탐구 이력을 대입 전략으로', status: 'soon', accent: 'lavender' },
    { slug: 'lab', name: '다빈치랩', short: '자기주도 학습관', status: 'soon', accent: 'mint' },
  ] as const satisfies ReadonlyArray<{ slug: ProgramSlug; name: string; short: string; status: 'open' | 'soon'; accent: 'mint' | 'lemon' | 'lavender' }>,
  why: [
    { title: '교육과정에서 출발', body: '2022 개정 교육과정 성취기준 원문에서 문항을 설계합니다.' },
    { title: '글로 남는 배움', body: '탐구와 논술의 결과가 학생의 글로 축적됩니다.' },
    { title: '원장님과 함께', body: '본사가 문항·지침서·자료를 만들고, 원장님은 수업에 집중합니다.' },
  ],
  contact: { email: 'davincischooloffice@gmail.com' },
  nav: [
    { href: '/programs/inquiry', label: '탐구보고서' },
    { href: '/programs/essay', label: '서논술형' },
    { href: '/programs/consulting', label: '대입 컨설팅' },
    { href: '/programs/lab', label: '다빈치랩' },
  ],
  header: { login: '로그인', franchise: '가맹문의' },
  hero: { ctaPrimary: '서논술형 수업 보기', ctaFranchise: '가맹문의' },
  sections: {
    programs: { eyebrow: 'PROGRAMS', title: '다빈치스쿨의 네 가지 수업' },
    why: { eyebrow: 'WHY DAVINCI', title: '왜 다빈치인가' },
  },
  franchiseCta: {
    title: '우리 지역에 다빈치스쿨을 열고 싶다면',
    body: '본사가 교재·문항·교사용 지침서를 준비합니다.',
    button: '가맹 안내 보기',
  },
  statusLabel: { open: '운영 중', soon: '준비 중' },
  footer: { contactLabel: '문의' },
}

export const programDetails: Record<ProgramSlug, { headline: string; paragraphs: string[]; bullets: string[] }> = {
  inquiry: {
    headline: '질문에서 보고서까지, 스스로 완성하는 탐구',
    paragraphs: ['5년간 40권의 교재로 다듬어진 탐구보고서 수업입니다. 학생은 질문을 세우고, 자료를 모으고, 보고서로 정리하는 과정을 학년별로 반복합니다.'],
    bullets: ['초·중·고 학년별 교재 40권', '주제 선정 → 자료 조사 → 보고서 작성의 3단계', '원장님용 수업 지도안 제공'],
  },
  essay: {
    headline: '성취기준에서 출발하는 서논술형 수업과 AI 피드백',
    paragraphs: ['2022 개정 교육과정 성취기준 원문에서 문항을 설계합니다. 학생이 답안을 제출하면 루브릭에 따라 AI가 채점하고, 잘한 점과 보완할 점을 나누어 피드백합니다.', '한 가지 대주제를 국어·영어·수학·과학·사회가 함께 다루는 융합(STEAM) 방식으로 문항을 구성합니다.'],
    bullets: ['초·중·고 × 국어·영어·수학·과학·사회(역사 포함)', '루브릭 기반 AI 채점, 30초 안에 피드백', '교사용 지침서·차시 설계·예시답안 제공'],
  },
  consulting: { headline: '탐구 이력을 대입 전략으로', paragraphs: ['준비 중입니다.'], bullets: [] },
  lab: { headline: '자기주도 학습관 다빈치랩', paragraphs: ['준비 중입니다.'], bullets: [] },
}

export const auth = {
  login: {
    title: '로그인',
    subtitle: '원장님·학생·관리자 모두 여기서 로그인합니다.',
    idLabel: '아이디 또는 이메일',
    passwordLabel: '비밀번호',
    submit: '로그인',
    submitting: '확인 중…',
    errors: {
      missing: '아이디와 비밀번호를 입력하세요.',
      invalid: '아이디 또는 비밀번호가 맞지 않습니다.',
    },
  },
}

/**
 * 학년을 정하지 않은 대주제·세트의 학교급 표기(대표 결정 2026-09-26: 2022 개정 성취기준은 학년군 단위).
 * 프롬프트 쪽 같은 낱말은 lib/studio/level-map.ts SCHOOL_BANDS — tests/themes.test.ts 가 둘이 같은지 본다.
 */
const GRADE_BAND: Record<string, { school: string; short: string; band: string } | undefined> = {
  초: { school: '초등학교', short: '초등', band: '3~6학년' },
  중: { school: '중학교', short: '중등', band: '1~3학년군' },
  고: { school: '고등학교', short: '고등', band: '1~3학년' },
}
/** "중 1학년" / 학년 없음 → "중등 · 1~3학년군" (목록·머리말·카드) */
const levelGradeShort = (level: string, grade: number | null) => {
  if (grade != null) return `${level} ${grade}학년`
  const b = GRADE_BAND[level]
  return b ? `${b.short} · ${b.band}` : level
}
/** "중 1학년" / 학년 없음 → "중학교(1~3학년군)" (세트 표지·문제지) */
/** 문장 고치기 칸 라벨의 두 번째 인자 — 그 문장을 담은 객체(lib/studio/editable-fields.ts EditableField.parent). */
type FieldParent = Record<string, unknown>
/** i번째(0부터) → 사람이 읽는 번호. */
const nth = (i: number | undefined) => (i ?? 0) + 1

const levelGradeLong = (level: string, grade: number | null) => {
  if (grade != null) return `${level} ${grade}학년`
  const b = GRADE_BAND[level]
  return b ? `${b.school}(${b.band})` : level
}

/**
 * 사회 세트 성취기준 고르기의 묶음 제목(대표 결정 2026-09-30). 열쇠는 성취기준 코드 머리(학년 숫자 + 과목 글자).
 * 고등학교 과목 이름은 2022 개정 교육과정 과목 이름이다. 표에 없는 머리는 "사회 (머리)"로 보인다.
 */
const SOCIAL_FAMILY_LABELS: Record<string, string> = {
  '4사': '사회 (초등 3~4학년군)',
  '6사': '사회 (초등 5~6학년군)',
  '9사(지리)': '지리',
  '9사(일사)': '일반사회',
  '9역-세계사': '역사 (세계사 영역)',
  '9역-한국사': '역사 (한국사 영역)',
  '9역': '역사',
  '10통사': '통합사회',
  '10한사': '한국사',
  '12세지': '세계시민과 지리',
  '12사문': '사회와 문화',
  '12한탐': '한국지리 탐구',
  '12도탐': '도시의 미래 탐구',
  '12정치': '정치',
  '12법사': '법과 사회',
  '12경제': '경제',
  '12국관': '국제 관계의 이해',
  '12여지': '여행지리',
  '12사탐': '사회문제 탐구',
  '12금융': '금융과 경제생활',
  '12기지': '기후변화와 지속가능한 세계',
  '12세사': '세계사',
  '12동역': '동아시아 역사 기행',
  '12역현': '역사로 탐구하는 현대 세계',
  // 도덕·윤리(2026-09-30) — 고등학교 과목 이름은 별책4 과목 표제 그대로
  '4도': '도덕 (초등 3~4학년군)',
  '6도': '도덕 (초등 5~6학년군)',
  '9도': '도덕',
  '12현윤': '현대사회와 윤리',
  '12윤사': '윤리와 사상',
  '12인윤': '인문학과 윤리',
  '12윤탐': '윤리문제 탐구',
}

export const app = {
  roleLabel: { admin: '본사 관리자', teacher: '원장님', student: '학생' },
  logout: '로그아웃',
  nav: {
    admin: [
      { href: '/admin', label: '대시보드' },
      { href: '/admin/academies', label: '가맹원 관리' },
      { href: '/admin/items', label: '문항 제작소' },
      { href: '/admin/inquiries', label: '가맹문의' },
      { href: '/admin/standards', label: '성취기준' },
      { href: '/admin/inquiry', label: '탐구보고서' },
    ],
    teacher: [
      { href: '/teacher', label: '홈' },
      { href: '/teacher/students', label: '학생 관리' },
      { href: '/teacher/items', label: '문항 찾기' },
      { href: '/teacher/assignments', label: '배정 현황' },
      { href: '/teacher/reports', label: '리포트' },
      { href: '/teacher/inquiry', label: '탐구보고서' },
    ],
    student: [
      { href: '/student', label: '내 과제' },
      { href: '/student/inquiry', label: '탐구보고서' },
    ],
  },
  dashboard: {
    admin: { title: '본사 대시보드', body: '가맹원·학생·채점 현황이 여기에 표시됩니다.' },
    teacher: {
      title: '원장님 홈',
      body: '학생 현황과 최근 결과가 여기에 표시됩니다.',
      stats: { pending: (n: number) => `검수 대기 ${n}건`, assignments: (n: number) => `진행 중 배정 ${n}개`, students: (n: number) => `학생 ${n}명` },
      links: { review: '검수하러 가기', assign: '문항 찾기', students: '학생 관리' },
    },
    student: { title: '내 과제', body: '아직 배정된 과제가 없어요.' },
  },
  adminInquiries: {
    title: '가맹문의 접수함',
    columns: { date: '접수', name: '이름', phone: '연락처', region: '지역', message: '내용', status: '상태' },
    statusLabel: { new: '신규', contacted: '연락함', done: '완료' } as const,
    empty: '아직 접수된 문의가 없습니다.',
  },
  adminAcademies: {
    listTitle: '가맹원 관리',
    columns: { code: '코드', name: '이름', region: '지역', teacherCount: '원장 수', studentCount: '학생 수' },
    newButton: '새 가맹원',
    form: {
      labels: { code: '원 코드', name: '원 이름', region: '지역', directorPhone: '원장 연락처' },
      submit: '등록',
    },
    teacherAccount: {
      heading: '원장 계정',
      formHeading: '원장 계정 발급',
      placeholders: { name: '원장님 이름', email: '원장님 이메일 (로그인 아이디)' },
      submit: '계정 발급',
      submitting: '발급 중…',
      issuedNotice: '아래 정보를 원장님께 전달하세요. 이 화면을 벗어나면 비밀번호를 다시 볼 수 없습니다.',
      labels: { id: '아이디:', password: '초기 비밀번호:' },
    },
    detailMeta: {
      studentCapacity: (n: number) => `학생 정원 ${n}`,
      monthlyGradingLimit: (n: number) => `월 채점 상한 ${n}건`,
    },
    errors: {
      codeInvalid: '원 코드는 영문 소문자·숫자 3~12자입니다.',
      nameRequired: '원 이름을 입력하세요.',
      codeTaken: '이미 있는 원 코드입니다.',
      teacherMissing: '이메일과 이름을 입력하세요.',
      invalidInput: '입력을 확인하세요.',
    },
  },
  adminStandards: {
    title: '성취기준 검증',
    filters: {
      levelLabel: '학교급',
      levelAll: '전체',
      subjectLabel: '과목 (교육부 분류)',
      subjectAll: '전체',
      subjectHelp: '제작소의 「사회」는 사회 + 한국사 + 세계사 + 도덕을 묶은 것입니다.',
      searchLabel: '검색',
      searchPlaceholder: '코드 또는 원문 검색',
      submit: '검색',
    },
    summary: (verified: number, total: number) => `검증 ${verified} / ${total}`,
    columns: { code: '코드', text: '원문', page: '쪽', status: '상태', action: '동작' },
    statusLabel: { verified: '검증됨', unverified: '미검증' },
    actions: { verify: '원문 확인', unverify: '해제' },
    empty: '조건에 맞는 성취기준이 없습니다.',
    pagination: { prev: '이전', next: '다음', pageOf: (page: number, total: number) => `${page} / ${total}` },
    crosscheck: {
      button: '원문 자동 대조',
      submitting: '대조 중…',
      result: (verifiedCount: number, mismatchedCount: number, unmatchedCount: number) =>
        `검증됨 ${verifiedCount}건 · 불일치 ${mismatchedCount}건 · 대조 불가 ${unmatchedCount}건`,
      mismatchHeading: '불일치 — 직접 확인 필요',
      mismatchColumns: { code: '코드', dbText: 'DB 원문', levelText: '성취수준 원문' },
      unmatchedNote: '성취수준 원문 자료가 없는 항목(고등학교 전 과목, 사회의 역사 영역 일부 등)은 자동 대조 대상이 아니며 미검증 상태로 남습니다.',
      error: '대조 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
  },
  studio: {
    gradeBand: GRADE_BAND,
    errors: {
      titleRequired: '대주제 제목을 입력하세요.',
      levelInvalid: '학교급을 선택하세요.',
      gradeInvalid: '학년을 확인하세요. (초 1~6, 중·고 1~3, 또는 학년 지정 안 함)',
      subjectsRequired: '과목을 1개 이상 선택하세요.',
      subjectInvalid: '알 수 없는 과목입니다.',
      subjectMerged: '한국사·세계사·도덕(윤리)은 사회로 묶였습니다. 사회를 선택하세요.',
      subjectNotInTheme: '대주제에 포함되지 않은 과목입니다.',
      subjectDuplicate: '이미 세트가 만들어진 과목입니다.',
      standardCountInvalid: '성취기준은 2~6개 선택하세요.',
      standardLevelMismatch: '대주제와 학교급이 다른 성취기준이 있습니다.',
      standardSubjectMismatch: '대주제와 과목이 다른 성취기준이 있습니다.',
      standardUnverified: (codes: string[]) => `원문 미검증 성취기준: ${codes.join(', ')}`,
      invalidStandards: '선택한 성취기준을 확인할 수 없습니다. 다시 선택해 주세요.',
      materialsInvalid: '공동 자료 형식을 확인하세요.',
      themeNotFound: '대주제를 찾을 수 없습니다.',
      saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
    themes: {
      title: '대주제 목록',
      newButton: '새 대주제',
      columns: {
        title: '제목',
        level: '학교급/학년',
        subjects: '과목',
        setCount: '세트 수',
        publishedCount: '게시 수',
        action: '동작',
      },
      open: '열기',
      empty: '아직 만들어진 대주제가 없습니다.',
    },
    newTheme: {
      title: '새 대주제',
      labels: { title: '제목', level: '학교급', grade: '학년(선택)', subjects: '과목' },
      subjectsHelp: '사회는 지리·일반사회·역사(한국사·세계사)·윤리(도덕)를 묶은 통합 과목입니다.',
      gradeNone: '학년 지정 안 함(학년군 전체)',
      gradeOption: (grade: number) => `${grade}학년`,
      gradeHelp: '2022 개정 성취기준은 학년군 단위입니다. 학년을 정하지 않으면 중학교는 1~3학년군, 초등학교는 3~6학년 수준으로 만듭니다. 초등은 1~6학년, 중등은 1~3학년 중에서 고를 수 있습니다.',
      submit: '만들기',
      submitting: '만드는 중…',
    },
    theme: {
      backToList: '← 목록으로',
      meta: (level: string, grade: number | null) => levelGradeShort(level, grade),
      gradeEdit: {
        label: '학년 바꾸기',
        help: '학년을 정하지 않으면 AI가 학교급 학년군 전체(중학교 1~3학년군, 초등학교 3~6학년) 수준으로 만듭니다. 바꾼 학년은 이 대주제의 세트에도 적용됩니다 — 이미 게시한 판은 다시 게시해야 표지가 바뀝니다.',
        submit: '바꾸기',
        submitting: '바꾸는 중…',
        saved: '학년을 바꿨습니다.',
      },
      addSubjects: {
        heading: '과목 추가',
        help: '대주제를 만들 때 고르지 않은 과목을 나중에 추가합니다.',
        submit: '추가',
        submitting: '추가하는 중…',
        saved: '과목을 추가했습니다.',
        nothingToAdd: '추가할 수 있는 과목이 없습니다.',
        remove: {
          help: '세트를 아직 만들지 않은 과목은 [빼기]로 대주제에서 뺄 수 있습니다.',
          button: '빼기',
          removing: '빼는 중…',
          removed: '과목을 뺐습니다.',
          hasSet: '이미 세트가 만들어진 과목은 뺄 수 없습니다.',
          lastSubject: '대주제에는 과목이 하나 이상 있어야 합니다.',
        },
      },
    },
    // 대주제 소개(0단계)는 검토 관문이 없다(2026-09-24 오너 결정) — AI 초안을 받아 고치거나 직접 써서 저장하면 바로 확정된다.
    intro: {
      heading: '대주제 소개',
      help: '대주제를 한눈에 소개하는 글과 과목별 접근 한 줄입니다. AI 초안을 받아 고치거나 직접 쓰고 저장하세요. 이 글은 이후 단계의 배경 설명과 세트 첫 장에 쓰입니다.',
      mockBadge: '가짜 응답',
      busy: '처리 중…',
      introLabel: '소개 문구 (3~4문장)',
      ideaLabel: (subject: string) => `${subject} 아이디어`,
      draftButton: 'AI 초안 받기',
      save: '저장',
      saved: '저장했습니다.',
      errors: {
        generic: '요청 처리 중 오류가 났습니다.',
        introTooShort: '소개 문구를 20자 이상 써 주세요.',
        ideaTooShort: '한 줄 아이디어를 5자 이상 써 주세요.',
      },
    },
    materials: {
      heading: '공동 자료',
      description: '이 대주제의 세트들이 골라 쓸 수 있는 공동 자료입니다. 세트마다 「이 세트에서 쓸 공동 자료」에서 체크한 것만 그 세트에 쓰입니다(기본은 아무것도 안 씀). 2A 스키마(JSON)를 그대로 붙여넣으세요.',
      submit: '저장',
      submitting: '저장 중…',
      saved: '저장했습니다.',
    },
    charts: {
      count: '도수',
      relative: '상대도수',
      value: '값',
    },
    sets: {
      heading: '세트 목록',
      newSetHeading: '세트 만들기',
      statusLabel: { draft: '초안', review: '검토중', published: '게시됨', retired: '내림' },
      progress: (n: number) => `${n}/5 확정`,
      open: '열기',
      empty: '아직 만들어진 세트가 없습니다.',
    },
    picker: {
      subjectLabel: '과목',
      subjectPlaceholder: '과목을 선택하세요',
      noSubjectsAvailable: '모든 과목에 이미 세트가 있습니다.',
      uncategorized: '미분류',
      // 사회 세트의 성취기준 묶음 제목(대표 결정 2026-09-30: 사회는 지리·일반사회·역사 등을 묶은 통합 과목).
      // 열쇠 = 코드 머리(lib/studio/subjects.ts standardFamilyKey). 표에 없는 코드 머리는 "사회 (코드 머리)"로 보인다.
      familyHelp: '사회는 통합 과목입니다. 지리·일반사회·역사·도덕(윤리) 어느 묶음에서든 골라 2~6개를 채우세요.',
      familyLabel: (key: string): string => SOCIAL_FAMILY_LABELS[key] ?? `사회 (${key})`,
      searchPlaceholder: '코드 또는 원문 검색',
      selectedCount: (n: number) => `${n}개 선택 (2~6개)`,
      verified: '검증됨',
      unverified: '미검증',
      unverifiedWarning: (codes: string[]) => `다음 성취기준은 원문 미검증입니다: ${codes.join(', ')}`,
      submit: '세트 만들기',
      submitting: '만드는 중…',
      empty: '해당 과목의 성취기준이 없습니다.',
    },
    // 세트별 공동 자료 선택(대표 결정 2026-09-28): 대주제 공동 자료 중 이 세트에서 쓸 것만 체크한다(기본 = 아무것도 안 씀).
    // 세트 화면(제작 탭 위 카드)과 세트 만들기 폼이 같이 쓴다. 배지 글자는 app.packageView.materials.sharedBadge 하나만 쓴다.
    sharedSelection: {
      heading: '이 세트에서 쓸 공동 자료',
      description: '체크한 대주제 공동 자료만 이 세트의 AI 생성·검토와 게시 판에 들어갑니다. 체크하지 않은 공동 자료는 이 세트에서 보이지도, 쓰이지도 않습니다.',
      createDescription: '기본은 아무것도 쓰지 않음입니다. 이 과목 수업·문항에 꼭 필요한 공동 자료만 체크하세요(세트를 만든 뒤에도 바꿀 수 있습니다).',
      empty: '이 대주제에는 공동 자료가 없습니다. 대주제 화면의 「공동 자료」 칸에서 먼저 넣을 수 있습니다.',
      idLabel: (id: string) => `자료 ${id}`,
      kindLabel: { table: '표', text: '글', chart: '그래프' } as Record<string, string>,
      noneSelected: '지금은 공동 자료를 쓰지 않습니다.',
      selectedSummary: (ids: string[]) => `쓰는 공동 자료: ${ids.map((id) => `자료 ${id}`).join(', ')}`,
      save: '공동 자료 선택 저장',
      saving: '저장 중…',
      saved: '저장했습니다. 다음 생성·미리보기·게시부터 이 선택을 씁니다.',
      regenNotice: '이미 3단계(차시 설계) 이후가 만들어져 있습니다. 공동 자료를 바꾸면 차시·자료·문항이 새 선택과 어긋날 수 있으니, 필요하면 3단계나 4단계부터 다시 생성하세요. 저장은 막지 않습니다.',
      errors: {
        invalid: (ids: string[]) => (ids.length ? `대주제에 없는 공동 자료입니다: ${ids.join(', ')}` : '공동 자료 선택을 확인하세요.'),
        saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
      },
    },
    wizard: {
      backToTheme: '← 세트 목록으로',
      versionLabel: (v: number) => `버전 ${v}`,
      stageNames: { 2: '재구성·목표·핵심질문', 3: '차시 설계', 4: '자료', 5: '평가', 6: '교사용 지침서', 7: '안내장 틀' } as Record<number, string>,
      // 대표 결정 2026-09-26: [생성] → 읽기 → [확인]. 검토는 참고(선택)이고 진행을 막지 않는다.
      stateLabel: { idle: '준비 전', generated: '생성됨', reviewed: 'AI 의견 받음', accepted: '확인됨', failed: '실패' },
      mockBadge: '가짜 응답',
      editedBadge: '편집됨',
      attemptLabel: (n: number) => `시도 ${n}`,
      regenerateConfirm: (stage: number, hasLater: boolean) => hasLater
        ? `이 단계를 다시 생성하면 지금 내용이 새 내용으로 바뀌고, ${stage + 1}~7단계가 초기화됩니다. 계속할까요?`
        : '이 단계를 다시 생성하면 지금 내용이 새 내용으로 바뀝니다. 계속할까요?',
      actions: {
        generate: '생성',
        review: 'AI 검토 의견 보기',
        accept: '확인',
        runDefaults: '기본값으로 진행',
        editJson: 'JSON 편집',
        cancelEdit: '취소',
        save: '저장',
      },
      busy: '처리 중…',
      empty: '아직 생성된 결과가 없습니다. [생성]을 눌러 시작하세요.',
      // 생성 직후 자동으로 도는 형식·원문 검사의 지적 — 참고용 메모(막지 않는다)
      notesHeading: '자동 검사 메모 (참고)',
      notesNone: '자동 검사에서 짚은 점이 없습니다.',
      // [AI 검토 의견 보기]를 눌렀을 때만 나온다 — 참고용
      aiReviewHeading: 'AI 검토 의견 (참고)',
      aiReviewNone: 'AI가 짚은 점이 없습니다.',
      errorPrefix: '오류: ',
      // AI 출력이 형식 검사(zod)를 통과하지 못했을 때 — 원인 문구(claude.ts)를 그대로 보여 주지 않고 이 안내를 앞에 두고, 원문은 작게 아래에 둔다
      parseErrorHeading: 'AI 출력이 형식 검사를 통과하지 못했습니다 — [생성]을 다시 누르세요.',
      prevStageHint: '이전 단계를 먼저 [확인]해야 진행할 수 있습니다.',
      keyQuestion: {
        heading: '핵심질문 선택',
        empty: '2단계를 확인하면 후보가 표시됩니다.',
        // 후보를 고르면 아래 칸에 그 문장이 채워지고, 고쳐 쓴 뒤 저장할 수 있다(대표 2026-09-26)
        editLabel: '핵심질문 문장 (후보를 고른 뒤 고쳐 쓸 수 있습니다)',
        editedHint: '후보를 고쳐 쓴 문장입니다.',
        select: '이 문장으로 저장',
        current: (q: string) => `현재 핵심질문: ${q}`,
        saved: '핵심질문을 저장했습니다.',
      },
      // 문장 고치기(대표 2026-09-26): 단계 출력의 문장만 칸으로 고친다. labels 키 = lib/studio/editable-fields.ts 의 경로(ix = 배열 번호들, 0부터)
      fieldEditor: {
        heading: '문장 고치기',
        description: '단계 결과의 문장만 칸에서 고칩니다. 저장하면 형식을 검사한 뒤 저장하고, 이 단계는 다시 [확인]해야 합니다. (구조를 바꾸려면 JSON 편집)',
        empty: '고칠 문장이 없습니다.',
        changedCount: (n: number) => `고친 칸 ${n}개`,
        save: '저장',
        saving: '저장 중…',
        saved: '저장했습니다. 이 단계를 다시 읽고 [확인]하세요.',
        reset: '고친 것 되돌리기',
        resetWarning: (from: number) => `${from}~7단계가 초기화됩니다. 계속할까요?`,
        resetConfirm: '네, 뒤 단계를 초기화하고 저장합니다',
        fieldError: (label: string, message: string) => `${label}: ${message}`,
        // 고르기 칸(역량 꼬리표)에서 아직 값이 없을 때의 첫 줄
        optionEmpty: '고르지 않음',
        groups: {
          reconstruction: () => '세트 재구성 문장',
          standards: (tag: string) => `성취기준 ${tag}`,
          learning_goals: () => '학습 목표',
          key_question_candidates: () => '핵심질문 후보',
          lessons: (tag: string) => `${tag}차시`,
          materials: (tag: string) => `자료 ${tag}`,
          items: (tag: string) => `${tag}번 문항`,
          feedback_templates: () => '피드백 문구',
          general: () => '세트 안내',
          glossary: () => '용어 풀이',
          merge_guide: () => '두 차시 합치기',
          grading_guide: () => '채점 안내',
          per_lesson: (tag: string) => `${tag}차시`,
          translations: () => '영문 자료·예시답안 번역 (교사용)',
        } as Record<string, (tag: string) => string>,
        labels: {
          // 2단계
          'reconstruction': () => '재구성 문장',
          'standards[].reconstructed_text': () => '재구성 문장',
          'learning_goals[].text': (ix: number[], p: FieldParent) => `학습 목표 ${nth(ix[0])} (${String(p.axis ?? '')})`,
          'key_question_candidates[]': (ix: number[]) => `후보 ${nth(ix[0])}`,
          // 3단계
          'lessons[].topic': () => '주제',
          'lessons[].goal': () => '목표',
          'lessons[].key_question': () => '차시 핵심질문',
          'lessons[].flow.intro[]': (ix: number[]) => `도입 ${nth(ix[1])}`,
          'lessons[].flow.main[].activities[]': (ix: number[]) => `전개 ${nth(ix[1])} · 활동 ${nth(ix[2])}`,
          'lessons[].flow.wrapup[]': (ix: number[]) => `정리 ${nth(ix[1])}`,
          'lessons[].teacher_script.questions[].prompt': (ix: number[]) => `발문 ${nth(ix[1])}`,
          'lessons[].teacher_script.questions[].expected_answer': (ix: number[]) => `발문 ${nth(ix[1])} 예상 답`,
          'lessons[].teacher_script.questions[].if_stuck': (ix: number[]) => `발문 ${nth(ix[1])} 막힐 때`,
          'lessons[].caution_notes[]': (ix: number[]) => `유의점 ${nth(ix[1])}`,
          'lessons[].worksheet.tasks[].prompt': (ix: number[], p: FieldParent) => `활동지 과제 ${nth(ix[1])} (${String(p.tier ?? '')})`,
          'lessons[].worksheet.tasks[].expected': (ix: number[]) => `활동지 과제 ${nth(ix[1])} 예상 답`,
          'lessons[].worksheet.self_check[]': (ix: number[]) => `자기평가 ${nth(ix[1])}`,
          'lessons[].formative_check.quiz[].q': (ix: number[]) => `퀴즈 ${nth(ix[1])} 문제`,
          'lessons[].formative_check.quiz[].answer': (ix: number[]) => `퀴즈 ${nth(ix[1])} 정답`,
          'lessons[].formative_check.quiz[].explanation': (ix: number[]) => `퀴즈 ${nth(ix[1])} 해설`,
          'lessons[].formative_check.quiz[].competency': (ix: number[]) => `퀴즈 ${nth(ix[1])} 역량`,
          // 4단계
          'materials[].title': () => '제목',
          'materials[].body': () => '본문',
          // 5단계
          'items[].stem': (_ix: number[], p: FieldParent) => `문두 (${String(p.kind ?? '')})`,
          'items[].conditions.items[].text': (ix: number[]) => `조건 ${nth(ix[1])}`,
          'items[].conditions.length': () => '분량',
          'items[].conditions.format': () => '형식',
          'items[].rubric.criteria[].name': (ix: number[]) => `채점 요소 ${nth(ix[1])} 이름`,
          'items[].rubric.criteria[].competency': (ix: number[]) => `채점 요소 ${nth(ix[1])} 역량`,
          'items[].rubric.criteria[].scale[].descriptor': (ix: number[], p: FieldParent) => `채점 요소 ${nth(ix[1])} · ${String(p.points ?? '')}점 기준`,
          'items[].rubric.holistic.상': () => '총체적 기준 상',
          'items[].rubric.holistic.중': () => '총체적 기준 중',
          'items[].rubric.holistic.하': () => '총체적 기준 하',
          'items[].rubric.notes[]': (ix: number[]) => `채점 유의점 ${nth(ix[1])}`,
          'items[].exemplar_answers[].text': (ix: number[], p: FieldParent) => `예시답안 ${nth(ix[1])} (${p.level ? String(p.level) : `${String(p.points ?? '')}점`})`,
          'feedback_templates.상': () => '상',
          'feedback_templates.중': () => '중',
          'feedback_templates.하': () => '하',
          // 6단계
          'general.purpose': () => '목적',
          'general.schedule_note': () => '일정 안내',
          'general.materials[]': (ix: number[]) => `준비물 ${nth(ix[0])}`,
          'glossary[].term': (ix: number[]) => `용어 ${nth(ix[0])}`,
          'glossary[].explanation': (ix: number[]) => `용어 ${nth(ix[0])} 풀이`,
          'merge_guide[].skip_activities[]': (ix: number[], p: FieldParent) => `${Array.isArray(p.lessons) ? p.lessons.join('·') : nth(ix[0])}차시 합칠 때 건너뛸 활동 ${nth(ix[1])}`,
          'grading_guide.common_errors[].error': (ix: number[], p: FieldParent) => `흔한 오답 ${nth(ix[0])} (${String(p.item_no ?? '')}번 문항)`,
          'grading_guide.common_errors[].how_to_read': (ix: number[]) => `흔한 오답 ${nth(ix[0])} 읽는 법`,
          'grading_guide.review_tips[]': (ix: number[]) => `검수 요령 ${nth(ix[0])}`,
          'grading_guide.retry_guidance': () => '재도전 안내',
          'per_lesson[].notes[]': (ix: number[]) => `메모 ${nth(ix[1])}`,
          // 6단계 영문 자료·영어 예시답안 번역(S-영-08, 교사용)
          'translations.materials[].title_ko': (_ix: number[], p: FieldParent) => `자료 ${String(p.material_id ?? '')} 제목 번역`,
          'translations.materials[].body_ko': (_ix: number[], p: FieldParent) => `자료 ${String(p.material_id ?? '')} 본문 번역`,
          'translations.exemplar_answers[].text_ko': (_ix: number[], p: FieldParent) => `${String(p.item_no ?? '')}번 문항 예시답안 ${String(p.label ?? '')} 번역`,
          // 7단계
          'per_lesson[].topic_summary': () => '배운 것 (60자 이내)',
          'per_lesson[].preview': () => '다음 차시 예고 (50자 이내)',
          'per_lesson[].home_study_suggestion': () => '가정 학습 제안 (60자 이내)',
          'per_lesson[].quiz_notes[].wrong_note': (_ix: number[], p: FieldParent) => `퀴즈 ${String(p.quiz_no ?? '')} 틀렸을 때 (40자 이내)`,
          'per_lesson[].criteria_phrases[].good[]': (ix: number[], p: FieldParent) => `${String(p.criterion_name ?? '')} · 잘한 점 ${nth(ix[2])}`,
          'per_lesson[].criteria_phrases[].improve[]': (ix: number[], p: FieldParent) => `${String(p.criterion_name ?? '')} · 더 할 점 ${nth(ix[2])}`,
        } as Record<string, (ix: number[], p: FieldParent) => string>,
      },
      stage2: {
        reconstructionLabel: '재구성 문장',
        goalsLabel: '학습 목표',
        goal: (text: string, axis: string) => `${text} (${axis})`,
        candidatesLabel: '핵심질문 후보',
      },
      // 3·4·6·7단계 탭은 요약이 아니라 완성본 그대로(오너 규칙 2026-09-26) — 차시 카드·자료·지침서·안내장 문구는 app.packageView 를 함께 쓴다
      stage3: {
        unitPlanHeading: '평가 계획',
        lessonsHeading: '차시 카드(원장 화면과 같은 모양)',
        guidePending: '각 차시의 「교사용 지침」 칸에 들어갈 지침서 메모는 6단계(교사용 지침서)를 만들면 함께 보입니다.',
      },
      stage4: {
        sharedNote: '「공동」 표시는 이 세트에서 쓰기로 체크한 대주제 공동 자료입니다. 이 세트의 차시·문항이 가리키는 것만 보입니다.',
        overriddenNote: (ids: string[]) => `${ids.map((id) => `자료 ${id}`).join(', ')}: 이 세트가 체크한 대주제 공동 자료와 ID가 겹쳐 게시 판에서는 공동 자료가 대신 실립니다.`,
      },
      // 5단계 요약(Stage5Summary.tsx): 문항 카드(조건·채점표·예시답안 전부) + 두 문항 공통 채점 기준표(등급표·피드백 틀)
      stage5: {
        itemsHeading: '문항',
        itemLabel: (no: number) => `${no}번`,
        pointsLabel: (n: number) => `${n}점`,
        lessonLabel: (no: number) => `${no}차시`,
        answerMode: { screen: '화면 입력', paper: '종이 답안(사진 제출)' } as Record<string, string>,
        situationLabel: '과제 상황',
        situation: (role: string, audience: string, purpose: string, product: string) => `${role} → ${audience} · ${purpose} · ${product}`,
        materialsLabel: '사용 자료',
        materialRef: (id: string) => `자료 ${id}`,
        conditionsHeading: '조건',
        conditionNo: (no: number) => `조건 ${no}.`,
        lengthLabel: '분량',
        formatLabel: '형식',
        overflowLabel: '초과 응답',
        rubricHeading: '채점표',
        criterionColumn: '평가 요소',
        pointColumn: (n: number) => `${n}점`,
        criterionLabel: (name: string, max: number) => `${name} (0~${max}점)`,
        conditionRefs: (nos: number[]) => (nos.length ? `조건 ${nos.join('·')}` : ''),
        noStep: '—',
        exampleLabel: '예',
        holisticHeading: '총체적 기준',
        levels: { 상: '상', 중: '중', 하: '하' },
        notesHeading: '채점 시 유의점',
        exemplarsHeading: '예시답안',
        exemplarCount: (itemNo: number, n: number) => `${itemNo}번 문항 예시답안 ${n}개`,
        exemplarLabel: (level: string | null, points: number) => `${level ?? ''} ${points}점`.trim(),
        exemplarScores: (scores: number[]) => `요소별 ${scores.join('·')}`,
        rationaleLabel: '채점자 의견',
        levelMapHeading: 'A~E 예상 점수',
        referencesHeading: '참고한 예시',
        commonHeading: '채점 기준표(공통)',
        commonNote: '두 문항 점수의 합으로 등급을 정합니다. 학생에게는 보이지 않습니다.',
        boundariesHeading: '등급표',
        boundaryColumns: { grade: '등급', range: '점수 범위', band: '수준', levelRef: '수준 참조' },
        boundaryRange: (min: number, max: number) => `${min}~${max}점`,
        feedbackHeading: '피드백 틀',
      },
      errors: {
        invalidJson: 'JSON 형식을 확인하세요.',
        invalidShape: (msg: string) => `형식이 올바르지 않습니다: ${msg}`,
        keyQuestionInvalid: '2단계를 먼저 확인해야 핵심질문을 정할 수 있습니다.',
        keyQuestionTooShort: (n: number) => `핵심질문은 ${n}자 이상으로 쓰세요.`,
        keyQuestionTooLong: (n: number) => `핵심질문은 ${n}자 이하로 쓰세요.`,
        prevNotAccepted: '이전 단계를 먼저 확인해야 이 단계를 수정할 수 있습니다.',
        tooFewStandards: '세트에 성취기준이 2개 이상 연결되어야 합니다.',
        saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        generic: '요청 처리 중 오류가 났습니다.',
        autoStopped: '생성이 실패해 자동 진행을 멈췄습니다. 멈춘 단계에서 [생성]을 다시 누르세요.',
      },
    },
    attachments: {
      heading: '이미지 첨부',
      description: '자료·차시에 이미지를 첨부합니다. (PNG·JPG·WEBP, 5MB 이하)',
      targetLabel: '첨부 대상',
      materialLabel: (id: string) => `자료 ${id}`,
      lessonLabel: (no: number) => `${no}차시`,
      noTargets: '자료 또는 차시를 먼저 생성해야 첨부할 수 있습니다.',
      fileLabel: '이미지 파일',
      upload: '업로드',
      uploading: '업로드 중…',
      empty: '첨부된 이미지가 없습니다.',
      delete: '삭제',
      thumbnailAlt: (target: string, n: number) => `${target} 첨부 이미지 ${n}`,
      errors: {
        invalidTarget: '첨부 대상을 확인하세요.',
        invalidUrl: '이미지 주소를 확인할 수 없습니다.',
        itemNotFound: '해당 자료·차시를 찾을 수 없습니다.',
        invalidShape: '이미지 목록 형식이 올바르지 않습니다.',
        saveFailed: '저장 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        uploadFailed: '업로드 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
        fileTooLarge: '파일 크기는 5MB 이하만 가능합니다.',
        invalidType: 'PNG·JPG·WEBP 파일만 업로드할 수 있습니다.',
      },
    },
    publish: {
      tabs: { wizard: '제작', preview: '미리보기' },
      heading: '게시',
      currentStatusLabel: '현재 상태',
      currentVersionLabel: (v: number) => `현재 버전 ${v}`,
      nextVersionLabel: (v: number) => `다음 버전 ${v}`,
      button: '게시하기',
      busy: '게시 중…',
      success: (v: number) => `버전 ${v}로 게시했습니다.`,
      blockersHeading: '아직 게시할 수 없습니다',
      blockers: {
        stageNotAccepted: (stage: number) => `${stage}단계를 아직 [확인]하지 않았습니다.`,
        unverifiedStandard: (code: string) => `성취기준 ${code}이(가) 원문 검증되지 않았습니다.`,
        noKeyQuestion: '핵심질문이 아직 선택되지 않았습니다.',
        quizChoice: (n: number) => `${n}차시 퀴즈에 선택지가 남아 있습니다 — 3단계를 다시 생성하세요.`,
        unknown: '게시할 수 없습니다. 단계·성취기준·핵심질문을 확인하세요.',
      },
      errors: {
        forbidden: '게시 권한이 없습니다.',
        saveFailed: '게시 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
      },
    },
  },
  packageView: {
    cover: {
      versionLabel: (v: number) => `버전 ${v}`,
      publishedAtLabel: '게시일',
      meta: (level: string, grade: number | null, subject: string) => `${levelGradeLong(level, grade)} · ${subject}`,
    },
    intro: '대주제 소개',
    standardsHeading: '성취기준',
    levelsHeading: '성취수준(A~E)',
    levelsToggle: '성취수준 보기',
    reconstructionHeading: '재구성',
    reconstructionTable: { columns: { code: '코드', original: '원문', type: '유형', reconstructed: '재구조화', reason: '이유', elements: '학습요소' } },
    learningGoalsHeading: '학습 목표',
    learningGoals: { axisLabel: (axis: string) => axis },
    keyQuestionHeading: '핵심 질문',
    unitPlanHeading: '평가 계획',
    unitPlan: {
      formativeLabel: '형성평가',
      placementLabel: '서·논술형 배치',
      rubricNoteLabel: '종합 도달 모습',
      placement: (kind: string, no: number) => `${kind} → ${no}차시`,
      lessonMapLabel: '차시 구성',
      lessonMapItem: (no: number, topic: string) => `${no}차시 ${topic}`,
    },
    answersToggle: '정답·채점 자료 펼치기',
    materialsHeading: '자료',
    // 관리자 미리보기만: 게시 판에서 뺀 자료(어느 문항·차시도 쓰지 않음, 대표 2026-09-26 — 세트는 실제로 쓰는 자료만 싣는다)
    materialsOmitted: (ids: string[]) => `게시 판에서 빠지는 자료: ${ids.map((id) => `자료 ${id}`).join(', ')} — 어느 문항·차시도 쓰지 않습니다.`,
    materials: {
      idLabel: '자료',
      imagesAlt: (title: string, n: number) => `${title} 첨부 이미지 ${n}`,
      sourceLabel: { 자작: '자작', 공개: '공개 자료' },
      aiBadge: 'AI 보조 · 확인 필요',
      roleLabel: { raw: '원자료', context: '배경' },
      // 대주제 공동 자료(이 세트가 체크한 것, 대표 결정 2026-09-28)를 세트 자료와 구별하는 배지 — 제작소 4·5단계 탭, 원장 패키지 화면,
      // 학생 화면, 문제지 인쇄, 공동 자료 선택 칸이 모두 이 한 키를 쓴다.
      sharedBadge: '공동',
      // 영어 세트의 공동 자료 영어판(S-영-09, 대표 2026-09-29) — 교사용 표시: 제작소 4단계 탭·원장 패키지 화면의 자료 칸에만(학생 화면·문제지 인쇄에는 없다).
      englishVersionBadge: (id: string) => `공동 자료 ${id}의 영어판`,
    },
    // 문항 = 자료 + 문항 한 덩어리(대표 연수 2기 p.18~20): 문항 카드 안에 그 문항의 자료를 <자료 1>·<자료 2> 상자로 넣는다.
    // 번호는 문항 안 번호(materials_used 순서), 옆의 작은 "자료 B"는 세트 자료 ID — 옛 문두("자료 B는 …")도 그대로 읽히게.
    items: {
      materialLabel: (n: number) => `<자료 ${n}>`,
      materialHint: (id: string) => `자료 ${id}`,
      materialMissing: (id: string) => `자료 ${id}을(를) 이 세트에서 찾을 수 없습니다.`,
      // 평가 요소(대표 2026-09-29 "평가 요소에 나와 있는 것들이 조건이라고 보면 된다"): 채점 요소 이름과 만점을 학생에게도 보인다 —
      // 학생 답안 칸·문제지 인쇄·원장 문항 카드·제작소 5단계 카드가 이 키를 같이 쓴다. 척도 서술·예시답안·A~E는 보이지 않는다.
      criteriaHeading: '평가 요소',
      criterionLine: (name: string, max: number) => `${name} (${max}점)`,
    },
    lessonsHeading: '차시',
    lessons: {
      columns: { no: '차시', standards: '담당 성취기준', keyQuestion: '차시 핵심질문', goal: '목표', assessment: '평가 배치', mergeable: '병합 가능' },
      noAssessment: '-',
      flow: { intro: '도입', main: '전개', wrapup: '정리' },
      materialsLabel: '사용 자료',
      quizHeading: '퀴즈',
      quiz: {
        typeLabel: { choice: '선택형', short: '단답형' },
        answerLabel: '정답',
        explanationLabel: '해설',
        answersHidden: '정답·해설은 원장님 화면에서만 표시됩니다.',
      },
      imagesAlt: (no: number, n: number) => `${no}차시 첨부 이미지 ${n}`,
      topicLabel: '주제',
      timeLabel: (i: number, m: number, w: number) => `도입 ${i}분 · 전개 ${m}분 · 정리 ${w}분`,
      stepLabel: (label: string, minutes: number) => `${label} (${minutes}분)`,
      scriptHeading: '발문 대본',
      scriptExpected: '예상 답',
      scriptStuck: '막힐 때',
      needsLabel: '준비물',
      cautionHeading: '지도상 유의점',
      // 차시 카드의 교사용 지침 칸(관리자·원장 화면만): 발문 대본 + 지도상 유의점 + 교사용 지침서의 그 차시 메모
      teacherBlockHeading: '교사용 지침',
      guideNotesHeading: '지침서 메모',
      // 교사용 지침 칸의 퀴즈 수준(L-10, 대표 2026-09-26: 성취수준 틀로 난이도를 나눈다) — 관리자·원장 화면만, 학생 화면에는 없다
      quizLevelsHeading: '퀴즈 수준',
      quizLevel: (no: number, level: string | undefined) => {
        const names: Record<string, string> = { 'D~E': '회상', C: '이해·적용', B: '관계·추론' }
        return level ? `${no}번 ${level}${names[level] ? `(${names[level]})` : ''}` : `${no}번 수준 없음`
      },
      // 역량 꼬리표(C-40, 단원 리포트 육각형 6축) — 퀴즈 문항·채점 요소 이름 옆 작은 배지. 관리자·원장 화면만, 학생 화면·문제지에는 없다
      competencyBadge: (competency: string) => `역량: ${competency}`,
      worksheetHeading: '활동지',
      worksheetTier: (tier: string, ref: string) => `${tier}(${ref})`,
      worksheetExpected: '기대 답',
      selfCheckHeading: '자기평가',
      mergeNoteLabel: '병합 시 생략',
      mergeableLabel: (no: number) => `${no}차시와 병합 가능`,
      assessmentSessionBadge: '단원 평가',
      // 분은 세트 구조(lib/studio/assessment-structure.ts ASSESSMENT_SESSION)에서 넘겨받는다
      assessmentSessionNote: (shortMin: number, essayMin: number) => `마지막 교수 차시 뒤에 서술형(${shortMin}분)과 논술형(${essayMin}분)을 함께 보는 평가 차시입니다. 퀴즈·활동지는 없고, 문항은 아래 평가 문항 카드에 있습니다.`,
    },
    teacherGuideHeading: '교사용 지침서',
    teacherGuide: {
      generalHeading: '전체 안내',
      materialsLabel: '준비물',
      scheduleLabel: '차시 운영 메모',
      purposeLabel: '수업 의도',
      glossaryHeading: '용어 설명',
      perLessonHeading: '차시별 유의점',
      lessonLabel: (no: number) => `${no}차시`,
      lessonWithTopic: (no: number, topic: string) => `${no}차시 · ${topic}`,
      mergeHeading: '병합 안내',
      mergeLabel: (a: number, b: number) => `${a}·${b}차시 병합`,
      mergeSkip: '생략 활동',
      mergeTime: (i: number, m: number, w: number) => `120분: 도입 ${i}분 · 전개 ${m}분 · 정리 ${w}분`,
      gradingHeading: '검수 요령',
      commonErrors: '흔한 오답',
      commonErrorItem: (itemNo: number) => `문항 ${itemNo}`,
      howToReadLabel: '이렇게 읽기',
      reviewTips: '검수 팁',
      retryLabel: '재도전 안내',
      // S-영-08(대표 2026-09-29 "영어 자료의 경우 비전공 원장님을 위해 영문 자료에 한국어 번역본을 첨부해서 교사용 지침서에 넣어줘"):
      // 원장 패키지 화면·제작소 6단계 탭의 지침서 안에만 — 학생 화면·문제지 인쇄에는 나오지 않는다
      translationsHeading: '영문 자료 번역 (교사용)',
      translationsNote: '비전공 원장님을 위한 한국어 번역입니다. 학생 화면과 문제지에는 나오지 않습니다.',
      translationsMaterial: (id: string, title?: string) => (title ? `<자료 ${id} · ${title}>` : `<자료 ${id}>`),
      translationsTitleLabel: '제목',
      translationsBodyLabel: '본문',
      translationsTableLabel: '표',
      translationsExemplarsHeading: '영어 예시답안 번역',
      translationsExemplarItem: (itemNo: number) => `문항 ${itemNo}`,
      translationsExemplarLabel: (label: string) => (/^\d+$/.test(label.trim()) ? `${label.trim()}점` : label),
    },
    assessmentHeading: '평가 문항',
    assessment: {
      kindLabel: { 서술형: '서술형', 논술형: '논술형' },
      lessonLabel: (no: number) => `${no}차시 연계`,
      pointsLabel: (n: number) => `${n}점`,
      conditions: {
        lengthLabel: '분량', requiredLabel: '필수 포함', formatLabel: '형식',
        heading: '조건',
        itemNo: (no: number) => `조건 ${no}.`,
        answerMode: { screen: '화면 입력', paper: '종이 답안(사진 제출)' },
        overflowLabel: '초과 응답',
        pointsLabel: (p: number) => `${p}점`,
      },
      elementsLabel: '출제 의도',
      situationLabel: '과제 상황',
      situation: (role: string, audience: string, purpose: string, product: string) => `${role} → ${audience} · ${purpose} · ${product}`,
      materialsLabel: '사용 자료',
      notesHeading: '채점 시 유의점',
      exemplarsHeading: '예시답안',
      exemplarLabel: (level: string | null, points: number) => `${level ?? ''} ${points}점`.trim(),
      exemplarScores: (scores: number[]) => `요소별 ${scores.join('·')}`,
      rationaleLabel: '채점자 의견',
      levelMapHeading: 'A~E 예상 점수',
      minCompetencyLabel: '최소 능력',
      referencesHeading: '참고한 공개 자료',
    },
    rubricHeading: '채점표',
    rubric: {
      criteriaLabel: '평가 요소',
      criterionLabel: (name: string, max: number) => `${name} (0~${max}점)`,
      axisLabel: '축',
      conditionsLabel: (nos: number[]) => (nos.length ? `조건 ${nos.join('·')}` : ''),
      // C-39(대표 2026-09-29): 요소가 평가하는 내용·표현을 가르친 교수 차시 — 교사용(원장 문항 카드·제작소 5단계 채점표), 학생 화면에는 없다
      taughtIn: (nos: number[]) => `배운 차시: ${nos.join('·')}차시`,
      // 역량 꼬리표(C-40, 단원 리포트 육각형 6축) — 요소 이름 옆 작은 배지. 교사용(원장 문항 카드·제작소 5단계 채점표), 학생 화면·문제지에는 없다
      competencyBadge: (competency: string) => `역량: ${competency}`,
      pointLabel: (n: number) => `${n}점`,
      exampleLabel: '예',
      holisticHeading: '총체적 기준',
    },
    shortRubric: { pointsLabel: '점수', expectationLabel: '기대 응답', exampleLabel: '예시' },
    extendedRubric: { criteriaLabel: '평가 요소', bandLabel: (n: number) => `${n}점` },
    gradingCriteriaHeading: '채점 기준',
    gradingCriteriaNote: '두 문항 점수의 합으로 등급을 정합니다. 문항별 채점표는 각 문항 카드에 있습니다.',
    gradeBoundariesHeading: '등급 경계표',
    gradeBoundaries: { gradeLabel: '등급', rangeLabel: '점수 범위', bandLabel: '수준', levelRefLabel: '수준 참조' },
    exemplarsHeading: '예시답안',
    exemplars: { levelLabel: { 상: '상', 중: '중', 하: '하' }, scoresLabel: '요소별 점수', totalLabel: (n: number) => `총점 ${n}`, gradeLabel: (n: number) => `${n}등급` },
    feedbackTemplatesHeading: '피드백 틀',
    feedbackLevels: { 상: '상', 중: '중', 하: '하' },
    noticePlanHeading: '안내장 틀',
    noticePlan: { lessonLabel: (n: number) => `${n}차시`, summary: '학습 요약', preview: '다음 차시', home: '가정 학습', quizNotes: '퀴즈 오답 코멘트', quizNoteNo: (n: number) => `${n}번`, phrases: '요소별 문구', good: '잘한 점', improve: '보완' },
    generatedWithHeading: '생성 모델',
    empty: '아직 내용이 없습니다.',
    // 문제지 인쇄(간단판): 표지·자료·문항·답란만 종이에 남긴다(app/globals.css 의 html.print-questions)
    print: {
      button: '문제지 인쇄',
      paperBox: '종이 답안 — 이 칸에 직접 쓰거나 그리세요.',
      studentLine: { name: '이름', date: '날짜' },
    },
  },
  teacherItems: {
    title: '문항 찾기',
    filters: {
      levelLabel: '학교급',
      levelAll: '전체',
      subjectLabel: '과목',
      subjectAll: '전체',
      submit: '검색',
    },
    card: {
      versionLabel: (v: number) => `버전 ${v}`,
      meta: (level: string, grade: number | null) => levelGradeShort(level, grade),
      open: '열기',
    },
    empty: '아직 게시된 문항이 없습니다.',
    detail: {
      backToList: '← 목록으로',
      notFoundTitle: '게시된 문항을 찾을 수 없습니다.',
    },
  },
  classroom: {
    print: '인쇄',
    students: {
      title: '학생 관리',
      columns: { name: '이름', grade: '학년', loginId: '아이디', assignments: '배정', actions: '동작' },
      empty: '아직 등록된 학생이 없습니다. 오른쪽에서 첫 학생을 추가하세요.',
      form: {
        heading: '학생 추가',
        nameLabel: '이름',
        levelLabel: '학교급',
        gradeLabel: '학년',
        submit: '추가',
        submitting: '만드는 중…',
      },
      issued: {
        heading: '계정이 만들어졌습니다',
        body: '아래 아이디와 초기 비밀번호는 지금 한 번만 보입니다. 인쇄하거나 복사해 학생에게 전해 주세요.',
        loginId: '아이디',
        password: '초기 비밀번호',
        copy: '복사',
        copied: '복사했습니다',
        close: '닫기',
      },
      reset: { button: '비밀번호 초기화', confirm: '새 비밀번호를 만들까요? 학생은 이전 비밀번호로 로그인할 수 없게 됩니다.', done: '새 비밀번호' },
      errors: {
        nameMissing: '이름을 입력하세요.',
        levelInvalid: '학교급을 고르세요.',
        gradeInvalid: '학년은 1~6 사이 숫자여야 합니다.',
        createFailed: '계정을 만들지 못했습니다. 잠시 후 다시 시도하세요.',
        forbidden: '권한이 없습니다.',
      },
    },
    assign: {
      button: '배정하기',
      newTitle: '배정하기',
      students: '학생 선택',
      selectAll: '전체 선택',
      alreadyAssigned: '이미 배정됨',
      gradeMismatch: (grade: number) => `세트 학년(${grade}학년)과 다릅니다`,
      dueLabel: '마감일',
      retryLabel: '재도전 허용',
      openLabel: '처음 열 차시 수',
      submit: '배정',
      submitting: '배정 중…',
      listTitle: '배정 현황',
      listEmpty: '아직 배정한 세트가 없습니다. 문항 찾기에서 세트를 열고 [배정하기]를 누르세요.',
      card: {
        students: (n: number) => `학생 ${n}명`,
        open: (n: number) => `${n}차시까지 열림`,
        pending: (n: number) => `검수 대기 ${n}건`,
        due: (d: string) => `마감 ${d}`,
        openButton: '열기',
      },
      detail: {
        backToList: '← 배정 현황으로',
        openLessons: '차시 열기',
        openTo: (n: number) => `${n}차시까지 열기`,
        applyAll: '반 전체에 적용',
        saved: '저장했습니다',
      },
      errors: {
        noStudents: '학생을 한 명 이상 고르세요.',
        setNotFound: '게시된 세트를 찾을 수 없습니다.',
        saveFailed: '저장하지 못했습니다. 다시 시도하세요.',
        invalidLessons: '차시 수가 올바르지 않습니다.',
      },
    },
    student: {
      listTitle: '내 과제',
      empty: '아직 배정된 과제가 없어요.',
      card: {
        due: (d: string) => `마감 ${d}`,
        progress: (open: number, quizDone: number, quizTotal: number, answerDone: number, answerTotal: number) =>
          `${open}차시까지 열림 · 퀴즈 ${quizDone}/${quizTotal} · 답안 ${answerDone}/${answerTotal}`,
        todo: '할 일 있음', reviewing: '선생님 확인 중', done: '결과 나옴', open: '열기',
      },
      lessonTab: (n: number) => `${n}차시`,
      // 마지막 교수 차시 뒤 단원 평가 차시(서술형 + 논술형, 대표 2026-09-26) 탭
      assessmentTab: (n: number) => `${n}차시 · 단원 평가`,
      assessmentIntro: (shortMin: number, essayMin: number) => `이 시간에는 서술형 문항(${shortMin}분)과 논술형 문항(${essayMin}분)에 차례로 답해요. 자료를 보면서 써도 돼요.`,
      locked: '아직 열리지 않았어요',
      keyQuestion: '이 시간의 질문',
      materials: '자료',
      quiz: {
        heading: '마무리 퀴즈',
        submit: '제출',
        submitted: (correct: number, total: number) => `${total}문항 중 ${correct}개 정답`,
        answerLabel: '정답', explanationLabel: '해설', yourAnswer: '내 답',
        shortPlaceholder: '답을 쓰세요',
        // 원장이 종이 O/X 를 넣은 문항 / 아직 O/X 가 없는 문항(설계 2026-09-29 §4.1)
        paperSolved: '종이로 푼 문제예요',
        noRecord: '아직 기록이 없어요',
      },
      paperAnswer: '이 문항은 표·그래프를 직접 작성하는 문항이에요. 종이에 풀어 선생님께 내세요. 선생님이 사진으로 올려 주시면 결과가 여기에 보여요.',
      conditionItem: (no: number) => `조건 ${no}`,
      answer: {
        heading: (label: string, points: number) => `${label} (${points}점)`,
        stem: '문항',
        conditions: '작성 조건 (아래 조건을 모두 지켜 쓰세요)',
        // 조건이 없는 문항(서술형, C-32)은 조건 머리글 없이 분량·형식만 보인다
        lengthFormat: '분량·형식',
        conditionLength: '분량:',
        conditionFormat: '형식:',
        chars: (n: number) => `${n}자`,
        saving: '저장 중…', saved: '임시저장됨',
        submit: '제출', confirm: '제출하면 고칠 수 없어요. 제출할까요?',
        submitted: '제출했어요. 선생님이 확인 중이에요.',
        tooShort: '조금 더 써 보세요. 조건을 다시 읽어 보세요. (50자 이상)',
        placeholder: '여기에 답안을 쓰세요',
      },
      errors: { notOpen: '아직 열리지 않은 차시예요.', alreadySubmitted: '이미 제출했어요.', saveFailed: '저장하지 못했어요. 다시 시도해 주세요.', paperOnly: '종이 답안 문항은 선생님이 사진으로 올려 주세요.' },
      result: {
        heading: (label: string) => `${label} 결과`,
        score: (s: number, max: number) => `${s}/${max}점`,
        criteria: '요소별 점수', evidence: '근거 문장',
        strengths: '잘한 점', improvements: '보완할 점', comment: '선생님 한마디',
        overall: (total: number, max: number, grade: number, band: string) => `종합 ${total}/${max}점 · ${grade}등급 · ${band}`,
        retry: '다시 써 보기',
        retryHint: '피드백을 보고 같은 문항에 한 번 더 답을 쓸 수 있어요. 첫 번째 답과 점수는 그대로 남아요.',
        attempt: (n: number) => `${n}회차`,
        firstAttempt: '1회차 답안과 피드백 보기',
      },
    },
    review: {
      quizHeading: '퀴즈 현황',
      quizRate: (pct: number) => `정답률 ${pct}%`,
      overrideCorrect: '정답 처리', overrideWrong: '오답 처리', noResponse: '—',
      // 종이 O/X 입력·차시별 최종 확인(단원 리포트 설계 2026-09-29 §4.1)
      quizCell: {
        labels: { empty: '빈칸', O: 'O', X: 'X' } as Record<'empty' | 'O' | 'X', string>,
        aria: (name: string, quizNo: number, state: string) => `${name} ${quizNo}번 — 지금 ${state}`,
        hintHeading: '칸을 누르면 바뀝니다',
        hints: [
          '빈칸 → O → X → 빈칸 (원장이 넣은 칸 · 종이로 푼 학생)',
          'O ↔ X (학생이 화면에서 푼 칸)',
        ],
        paperMark: '종이',
        studentAnswer: (response: string) => `학생이 쓴 답: ${response}`,
        teacherEntered: '원장이 넣은 칸(종이로 푼 문제)',
        notOpen: '아직 열지 않은 차시라 O/X 를 넣을 수 없습니다.',
      },
      fillEmpty: '종이로 푼 학생 O 채우기',
      fillEmptyHint: '누르면 학생 목록이 나옵니다. 종이로 푼 학생만 골라 빈칸을 O 로 채우고, 그다음 틀린 칸만 눌러 X 로 바꾸세요.',
      fillEmptyAbsentHint: '결석한 학생과 이 차시를 아직 열지 않은 학생은 채우지 않습니다.',
      fillPick: {
        heading: '종이로 푼 학생만 체크하세요',
        confirm: '선택한 학생의 빈칸을 O로',
        cancel: '취소',
      },
      finalize: {
        heading: (lessonNo: number) => `${lessonNo}차시 최종 확인`,
        tabDone: (tab: string) => `${tab} ✓`,
        button: '최종 확인',
        done: (date: string) => `최종 확인됨 · ${date}`,
        undo: '확인 풀기',
        reportNote: '최종 확인한 차시만 단원 리포트에 들어갑니다.',
        changeNote: '최종 확인 뒤에 O/X 를 바꾸면 그 학생의 확인이 풀립니다.',
        unfinalized: 'O/X 를 바꿔 이 차시의 최종 확인이 풀렸습니다. 다 고친 뒤 [최종 확인]을 다시 눌러 주세요.',
        pendingHeading: '확인이 풀린 학생',
        missingHeading: '아직 O/X 가 없는 학생',
        missingNote: '그대로 최종 확인해도 됩니다. 빈칸은 리포트에서 "기록 없음"으로 빠집니다.',
      },
      answersHeading: '답안·검수',
      status: { none: '미제출', pending: '채점 중', drafted: '검수 대기', confirmed: '공개됨', failed: '실패', rejected: '다시 쓰기 요청', retry: '재도전 중' },
      attempt: (n: number) => `${n}회차`,
      studentAnswer: '학생 답안',
      aiDraft: 'AI 초안', finalLabel: '확정본',
      mock: '가짜 응답',
      criteria: '요소별 점수', evidence: '근거', score: '문항 점수',
      strengths: '잘한 점', improvements: '보완할 점', addLine: '문장 추가', remove: '지우기',
      comment: '원장 코멘트', adjustNote: '조정 이유(선택)',
      confirmAsIs: '그대로 확정', confirmEdited: '수정하여 확정', regrade: 'AI 다시 채점', requestRegrade: '재채점 요청(본사)', reopen: '다시 고치기',
      confirmedAt: (at: string) => `공개됨 · ${at}`,
      overall: (total: number, max: number, grade: number, band: string) => `종합 ${total}/${max}점 · ${grade}등급 · ${band}`,
      overallPending: '서·논술형 문항이 모두 확정되면 종합 점수가 나옵니다.',
      compare: (a1: number, a2: number) => `1회차 ${a1}점 → 2회차 ${a2}점`,
      errors: {
        saveFailed: '저장하지 못했습니다.', notDrafted: '검수 대기 상태가 아닙니다.', badScore: '점수가 범위를 벗어났습니다.',
        quizCellNotAllowed: '이 칸은 바꿀 수 없습니다.',
        quizLessonNotOpen: '이 학생에게 아직 열지 않은 차시입니다. 차시를 연 뒤에 O/X 를 넣어 주세요.',
        fillNoneSelected: '채울 학생을 한 명 이상 체크해 주세요.',
        unfinalizeFailed: 'O/X 는 저장했습니다. 다만 최종 확인을 풀지 못했습니다. [확인 풀기]를 누른 뒤, 다 고치고 [최종 확인]을 다시 눌러 주세요.',
        undoFailed: '최종 확인을 풀지 못했습니다. 잠시 뒤 다시 눌러 주세요.',
        finalizeFailed: '최종 확인을 저장하지 못했습니다. 잠시 뒤 다시 눌러 주세요.',
        manualNoRegrade: '종이 답안 점수는 원장이 직접 넣은 것이라 AI 가 다시 채점하지 않습니다.',
        paperAlreadySubmitted: '이미 제출된 답안이 있습니다. 아래 검수 카드에서 확인해 주세요.',
      },
      // 종이 답안 점수 입력(단원 리포트 설계 2026-09-29 §4.2, R-5)
      paper: {
        // answers.body 에 들어가는 표지 — 원장 검수 카드와 학생 화면(읽기 전용)에 그대로 보인다
        marker: '종이 답안 — 종이에 쓴 답을 선생님이 직접 채점했습니다.',
        badge: '종이 답안',
        open: '종이 답안 점수 입력',
        close: '접기',
        intro: '종이에 쓴 답안을 보면서 요소마다 점수를 하나씩 고르세요. 저장하면 바로 확정됩니다.',
        editIntro: '점수를 고친 뒤 저장하면 다시 확정됩니다.',
        criterionMax: (max: number) => `${max}점 만점`,
        scaleLine: (points: number, descriptor: string) => `${points}점 — ${descriptor}`,
        total: (total: number, max: number) => `합계 ${total} / ${max}점`,
        chooseAll: '요소마다 점수를 하나씩 골라 주세요.',
        comment: '원장 코멘트(선택)',
        save: '저장',
        saved: '저장했습니다.',
        draftWarning: '학생이 쓰다 만 글이 있습니다. 저장하면 그 글은 종이 답안으로 바뀌어 남지 않습니다.',
      },
    },
    // 학생별 차시 안내장(v2 T8) — 원장 화면에서 초안 → 확정 → 인쇄. 학교생활기록부가 아니다.
    notice: {
      title: (name: string, no: number) => `${name} · ${no}차시 안내장`,
      docTitle: '차시별 피드백 안내장',
      back: '← 배정 상세로',
      cardHeading: '안내장',
      cardLink: (no: number) => `${no}차시`,
      draft: '안내장 초안 만들기', redraft: '다시 만들기', drafting: '만드는 중…',
      redraftConfirm: '초안을 다시 만들면 고친 문장이 새 초안으로 바뀝니다(참여 관찰·원장 한마디는 그대로 둡니다). 다시 만들까요?',
      confirm: '확정', reconfirm: '고쳐서 다시 확정', confirming: '저장 중…', confirmed: '확정했습니다.',
      print: '인쇄', printHint: '확정한 안내장만 인쇄할 수 있습니다.',
      status: { draft: '초안(확정 전)', confirmed: '확정' },
      confirmedAt: (at: string) => `확정 ${at}`,
      student: '학생', date: '수업일',
      sections: { context: '이번 차시 학습 내용', participation: '참여·퀴즈 결과', essay: '서·논술형 결과', next: '다음 차시·가정 학습', director: '원장 한마디' },
      keyQuestion: '핵심 질문', goal: '학습 목표', summary: '오늘 배운 것',
      quizResult: (c: number, t: number) => `${t}문항 중 ${c}개 정답`,
      quizCols: { no: '번호', q: '문항', result: '결과', note: '코멘트' },
      quizCorrect: '정답', quizWrong: '다시 보기',
      score: (s: number, t: number, band: string) => `${s}/${t}점 · ${band}`,
      criteriaCols: { name: '평가 요소', score: '점수', good: '잘한 점', improve: '보완할 점' },
      criterionScore: (s: number, m: number) => `${s}/${m}`,
      retry: (b: number, a: number) => `1회차 ${b}점에서 출발 → 재도전 ${a}점`,
      preview: '다음 시간', homeStudy: '가정 학습 제안',
      directorCommentLabel: '참여 관찰(원장 작성)', directorMessageLabel: '원장 한마디',
      edit: {
        heading: '문장 고치기',
        hint: '점수·정오는 확정 채점에서 그대로 옵니다. 문장만 고칠 수 있습니다. 참여 관찰·원장 한마디는 비워 두면 안내장에서 빠집니다.',
        topicSummary: '학습 요약', quizNote: (n: number) => `퀴즈 ${n} 코멘트`,
        good: (name: string) => `${name} · 잘한 점`, improve: (name: string) => `${name} · 보완할 점`,
        improvementFor: (kind: string) => `${kind} 재도전 코멘트`, preview: '다음 차시 예고', homeStudy: '가정 학습 제안',
        directorComment: '참여 관찰(구체 행동과 함께)', directorMessage: '원장 한마디',
        maxChars: (n: number, max: number) => `${n}/${max}자`,
      },
      lintHeading: '문장 규칙 확인(고친 뒤 다시 눌러 주세요)',
      noNotice: '아직 안내장이 없습니다. 확정된 채점과 퀴즈 결과로 초안을 만듭니다.',
      errors: {
        notFound: '배정을 찾을 수 없습니다.',
        noPlan: '이 세트에는 안내장 틀이 없습니다(v2 게시본만 지원).',
        badLesson: '차시 번호가 올바르지 않습니다.',
        invalid: '안내장 모양이 올바르지 않습니다.',
        lint: '문장 규칙 위반이 있어 저장하지 않았습니다.',
        stale: '초안을 만든 뒤 채점이나 퀴즈 결과가 바뀌었습니다. [다시 만들기]를 눌러 주세요.',
        noDraft: '먼저 초안을 만들어 주세요.',
        aiFailed: 'AI 초안을 만들지 못했습니다. 잠시 후 다시 시도해 주세요.',
        saveFailed: '저장에 실패했습니다.',
      },
    },
    // 단원 리포트(설계 2026-09-29 §5) — 학생 한 명 × 대주제 하나, 수업한 과목을 모두 합친 한 부. 원장이 확인하고 인쇄한다.
    // 조사가 앞 낱말의 받침에 따라 달라지지 않게, 끼워 넣는 말 뒤에는 늘 같은 낱말(역량·학생·단원)을 둔다.
    report: {
      docTitle: '단원 리포트',
      index: {
        title: '단원 리포트',
        intro: [
          '단원이 끝나면 학생마다 리포트 한 부를 냅니다.',
          '그 단원에서 수업한 과목이 모두 한 부에 들어갑니다.',
        ],
        empty: '아직 배정한 세트가 없습니다. 세트를 배정하면 여기에 학생이 나옵니다.',
        open: '리포트 보기',
        status: { none: '리포트 없음', draft: '초안', confirmed: '확정' } as Record<'none' | 'draft' | 'confirmed', string>,
        readiness: (subject: string, finalized: number, lessons: number, confirmed: number, items: number) =>
          `${subject} — 퀴즈 확인 ${finalized}/${lessons}차시 · 평가 확정 ${confirmed}/${items}문항`,
        unreadable: (subject: string) => `${subject} — 세트 내용을 읽지 못했습니다.`,
        loadFailed: '리포트 목록을 읽지 못했습니다. 잠시 뒤에 이 화면을 다시 열어 주세요.',
        finalizeUnavailable: '퀴즈 최종 확인 기록을 아직 읽을 수 없습니다. 준비되면 퀴즈 확인 수가 채워집니다.',
        reportsUnavailable: '리포트 저장 칸이 아직 준비되지 않았습니다. 미리보기와 인쇄는 그대로 할 수 있습니다.',
      },
      page: {
        back: '← 리포트 목록으로',
        title: (name: string) => `${name} 학생 단원 리포트`,
        status: { none: '저장 전', draft: '초안', confirmed: '확정' } as Record<'none' | 'draft' | 'confirmed', string>,
        confirmedAt: (at: string) => `확정 ${at}`,
        subjectsHeading: '넣을 과목',
        subjectsHint: '체크한 과목만 리포트에 들어갑니다. 육각형과 종합 코멘트도 체크한 과목으로 다시 계산합니다.',
        subjectsNone: '과목을 하나도 고르지 않으면 배정된 과목이 모두 들어갑니다.',
        attitudeHeading: '수업 태도 한 줄',
        attitudeHint: '낱말만 고르면 종합 코멘트의 첫 줄이 완성됩니다.',
        attitudeGroups: { participation: '참여', traits: '수업 모습', closing: '마무리' } as Record<'participation' | 'traits' | 'closing', string>,
        attitudeTraitsHint: '한 개나 두 개를 골라 주세요.',
        attitudePreview: '완성된 문장',
        attitudeEmpty: '수업 태도 줄이 비어 있습니다. 낱말을 고르면 종합 코멘트 첫 줄에 들어갑니다. 고르지 않아도 저장·확정·인쇄는 그대로 할 수 있습니다.',
        attitudeIncomplete: (missing: string[]) => `세 가지를 모두 고르면 문장이 완성됩니다. 아직 고르지 않은 것: ${missing.join(', ')}`,
        attitudeClear: '고른 낱말 지우기',
        previewHeading: '미리보기',
        saveDraft: '초안 저장', confirm: '확정', reopen: '다시 고치기', print: '인쇄', saving: '저장 중…',
        saved: '초안을 저장했습니다.',
        confirmed: '확정했습니다.',
        reopened: '다시 고칠 수 있습니다.',
        numbersNote: '점수와 O/X 는 저장할 때의 기록으로 들어갑니다.',
        confirmedHint: '확정한 리포트입니다. 문장이나 과목을 바꾸려면 [다시 고치기]를 눌러 주세요.',
        printHint: '초안도 인쇄할 수 있습니다. 확정 전에는 종이에 「초안」 표시가 함께 찍힙니다.',
        stale: '저장한 뒤에 점수나 O/X 가 바뀌었습니다. 아래 미리보기는 저장해 둔 내용입니다.',
        staleFirst: '먼저 [점수 다시 불러오기]를 눌러 지금 점수를 확인해 주세요. 그다음에 [초안 저장]과 [확정]을 누를 수 있습니다.',
        storedUnreadable: '저장된 리포트를 읽지 못해 새로 만듭니다.',
        unreadableSubjects: (subjects: string[]) => `세트 내용을 읽지 못해 리포트에 넣지 못한 과목: ${subjects.join(', ')}`,
        staleConfirmed: '확정한 뒤에 점수나 O/X 가 바뀌었습니다. [다시 고치기]를 누른 다음 [점수 다시 불러오기]를 눌러 주세요.',
        reload: '점수 다시 불러오기',
        reloaded: '지금 기록으로 점수를 다시 불러왔습니다. 고친 문장은 그대로 두었습니다. [초안 저장]이나 [확정]을 누르면 저장됩니다.',
        finalizeUnavailable: '퀴즈 최종 확인 기록을 아직 읽을 수 없어 퀴즈 결과가 비어 있습니다. 평가 문항 점수는 그대로 들어갑니다.',
        reportsUnavailable: '리포트 저장 칸이 아직 준비되지 않았습니다. 미리보기와 인쇄는 그대로 할 수 있습니다.',
        notReady: {
          heading: '리포트를 만들 수 없습니다',
          forbidden: '이 학생의 리포트를 볼 수 없습니다.',
          notFound: '학생이나 단원을 찾을 수 없습니다.',
          noAssignments: '이 단원에서 이 학생에게 배정된 세트가 없습니다.',
          loadFailed: '기록을 읽지 못했습니다. 잠시 뒤에 이 화면을 다시 열어 주세요.',
        },
      },
      view: {
        draftMark: '초안',
        frontLabel: '단원 리포트',
        student: '학생', theme: '단원', date: '날짜', subjects: '과목',
        studentName: (name: string) => `${name} 학생`,
        radarHeading: '역량 육각형',
        radarAria: (name: string) => `${name} 학생 역량 육각형`,
        sparseNote: '문항 수 적음',
        // 역량 뜻 표(학부모가 읽는다): 역량 | 뜻 | 점수 — 한 줄에 역량 하나
        axesHeading: '역량은 이렇게 봅니다',
        axesColumns: { competency: '역량', meaning: '뜻', score: '점수' },
        meanings: {
          '지식·이해': '배운 개념과 용어를 정확히 알고 있는가',
          '자료 읽기': '표·글·그림에서 필요한 정보를 찾아내는가',
          '근거 들어 설명하기': '이유와 근거를 들어 자기 생각을 설명하는가',
          '글로 표현하기': '읽는 사람이 이해하기 쉽게 문장과 글로 쓰는가',
          '과정·기능': '계산, 절차, 탐구 방법을 순서에 맞게 해내는가',
          '가치·태도': '무엇이 중요한지 판단하고 실천하려는 마음을 보이는가',
        } as Record<'지식·이해' | '자료 읽기' | '근거 들어 설명하기' | '글로 표현하기' | '과정·기능' | '가치·태도', string>,
        axisScore: (earned: number, possible: number, count: number) => `${earned}/${possible}점 · 문항 ${count}개`,
        axisEmpty: '이번 단원 기록 없음',
        summaryHeading: '과목별 한 줄 요약',
        overallHeading: '종합 코멘트',
        overallLabels: { attitude: '수업 태도', strength: '잘한 점', practice: '더 연습할 점', subject: '과목 한마디' } as Record<'attitude' | 'strength' | 'practice' | 'subject', string>,
        basisNote: '이번 단원 수업 기준의 기록입니다.',
        detailHeading: '과목별 상세',
        keyQuestion: '핵심 질문',
        quizHeading: '차시 퀴즈',
        quizScore: (correct: number, total: number) => `${total}문항 중 ${correct}문항 정답`,
        lesson: (no: number) => `${no}차시`,
        markCorrect: 'O', markWrong: 'X',
        markAria: (quizNo: number, correct: boolean) => `${quizNo}번 ${correct ? 'O' : 'X'}`,
        wrongHeading: '다시 볼 문제',
        wrongQuestion: (quizNo: number, question: string) => `${quizNo}번 · ${question}`,
        quizNone: '확인된 퀴즈 기록이 없습니다.',
        assessmentHeading: '평가 문항',
        itemLine: (kind: string, points: number, max: number) => `${kind} — ${points}/${max}점`,
        criterionLine: (name: string, points: number, max: number) => `${name} — ${points}/${max}점`,
        assessmentNone: '확정된 평가 문항이 없습니다.',
        missingHeading: '아직 들어가지 않은 것',
        missingLessons: (lessons: number[]) => `아직 확인되지 않은 차시: ${lessons.map((n) => `${n}차시`).join(', ')}`,
        missingQuiz: (cells: { lesson_no: number; quiz_no: number }[]) => `기록이 없는 퀴즈 문항: ${cells.map((c) => `${c.lesson_no}차시 ${c.quiz_no}번`).join(', ')}`,
        missingItems: (kinds: string[]) => `아직 확정되지 않은 평가 문항: ${kinds.join(', ')}`,
      },
      edit: {
        heading: '문장 고치기',
        hint: '문장만 고칠 수 있습니다. 점수와 O/X 는 확인한 기록에서 그대로 옵니다. 칸을 비우면 그 줄은 리포트에서 빠집니다.',
        overallLine: { attitude: '종합 코멘트 · 수업 태도', strength: '종합 코멘트 · 잘한 점', practice: '종합 코멘트 · 더 연습할 점', subject: '종합 코멘트 · 과목 한마디' } as Record<'attitude' | 'strength' | 'practice' | 'subject', string>,
        summary: (subject: string) => `${subject} 한 줄 요약`,
        quizNote: (subject: string, lessonNo: number, quizNo: number) => `${subject} ${lessonNo}차시 퀴즈 ${quizNo}번 코멘트`,
        phrase: (subject: string, kind: string, name: string) => `${subject} ${kind} · ${name}`,
        phraseKind: { good: '잘한 점', improve: '보완할 점' } as Record<'good' | 'improve', string>,
        restore: '기본 문장으로',
        maxChars: (n: number, max: number) => `${n}/${max}자`,
      },
      // buildUnitReport 에 넘기는 문장 틀(lib/classroom/report.ts UnitReportCopy)
      build: {
        subjectSummary: {
          quizAndAssessment: (a: { subject: string; quizCorrect: number; quizTotal: number; assessmentPoints: number; assessmentMax: number }) =>
            `${a.subject} — 퀴즈 ${a.quizTotal}문항 중 ${a.quizCorrect}문항 정답, 평가 문항 ${a.assessmentMax}점 중 ${a.assessmentPoints}점`,
          quizOnly: (a: { subject: string; quizCorrect: number; quizTotal: number }) =>
            `${a.subject} — 퀴즈 ${a.quizTotal}문항 중 ${a.quizCorrect}문항 정답`,
          assessmentOnly: (a: { subject: string; assessmentPoints: number; assessmentMax: number }) =>
            `${a.subject} — 평가 문항 ${a.assessmentMax}점 중 ${a.assessmentPoints}점`,
          none: (a: { subject: string }) => `${a.subject} — 아직 확인된 기록이 없습니다.`,
        },
        overall: {
          strongAndWeak: (a: { studentName: string; strong: string; weak: string }) =>
            `${a.studentName} 학생은 이번 단원에서 「${a.strong}」 역량이 돋보였고, 「${a.weak}」 역량은 조금 더 연습하면 좋겠습니다.`,
          even: (a: { studentName: string }) => `${a.studentName} 학생은 이번 단원에서 여러 역량을 고르게 보여 주었습니다.`,
          neutral: (a: { studentName: string; themeTitle: string }) => `${a.studentName} 학생의 「${a.themeTitle}」 단원 학습 기록입니다.`,
          // 첫 줄(수업 태도): 원장이 낱말만 골라 완성한다. 낱말 뒤에는 늘 같은 말(참여하였고·모습과·모습을)이 온다.
          attitudeWords: {
            participation: { active: '적극적으로', steady: '꾸준히', calm: '차분하게', growing: '조금씩 더 활발하게' } as Record<'active' | 'steady' | 'calm' | 'growing', string>,
            traits: {
              asks: '질문을 자주 하는', speaks: '자기 생각을 분명히 말하는', listens: '친구의 의견을 잘 듣는',
              focuses: '끝까지 집중하는', completes: '맡은 활동을 성실히 마치는', retries: '어려운 문제도 다시 시도하는',
            } as Record<'asks' | 'speaks' | 'listens' | 'focuses' | 'completes' | 'retries', string>,
            closing: { expect: '앞으로가 더 기대됩니다', steady: '꾸준함이 돋보입니다', confidence: '자신감이 자라고 있습니다', growth: '성장이 눈에 보입니다' } as Record<'expect' | 'steady' | 'confidence' | 'growth', string>,
          },
          attitude: (a: { studentName: string; participation: 'active' | 'steady' | 'calm' | 'growing'; traits: ('asks' | 'speaks' | 'listens' | 'focuses' | 'completes' | 'retries')[]; closing: 'expect' | 'steady' | 'confidence' | 'growth' }): string => {
            const w = app.classroom.report.build.overall.attitudeWords
            const looks = a.traits.map((t, i) => `${w.traits[t]} ${i < a.traits.length - 1 ? '모습과' : '모습을'}`).join(' ')
            return `${a.studentName} 학생은 이번 단원 수업에 ${w.participation[a.participation]} 참여하였고, ${looks} 보였습니다. ${w.closing[a.closing]}.`
          },
          // 근거 한 문장: 채점 요소(과목·문항 종류·요소 이름·점수) 또는 퀴즈(과목·역량·문항 수)
          evidence: (axis: string, e: { kind: 'criterion'; subject: string; itemKind: string; name: string; points: number; max: number } | { kind: 'quiz'; subject: string; correct: number; total: number }): string =>
            e.kind === 'criterion'
              ? `${e.subject} ${e.itemKind} 「${e.name}」 요소에서 ${e.max}점 중 ${e.points}점을 받았습니다.`
              : `${e.subject} 퀴즈의 「${axis}」 문항 ${e.total}개 중 ${e.correct}개를 맞혔습니다.`,
          strength: (a: { axis: string; evidence: { kind: 'criterion'; subject: string; itemKind: string; name: string; points: number; max: number } | { kind: 'quiz'; subject: string; correct: number; total: number } }): string =>
            `「${a.axis}」 역량이 가장 돋보였습니다. ${app.classroom.report.build.overall.evidence(a.axis, a.evidence)}`,
          practiceGeneric: '배운 내용을 하루에 한 가지씩 다시 읽고 짧게 써 보면 좋겠습니다.',
          practice: (a: { axis: string; evidence: { kind: 'criterion'; subject: string; itemKind: string; name: string; points: number; max: number } | { kind: 'quiz'; subject: string; correct: number; total: number }; action: string | null }): string =>
            `「${a.axis}」 역량은 조금 더 연습하면 좋겠습니다. ${app.classroom.report.build.overall.evidence(a.axis, a.evidence)} ${a.action ?? app.classroom.report.build.overall.practiceGeneric}`,
          subject: (a: { best: string; focus: string | null }): string =>
            a.focus
              ? `이번 단원에서는 ${a.best} 과목의 기록이 가장 좋았습니다. 다음 단원에서는 ${a.focus} 과목에 조금 더 힘을 실어 보면 좋겠습니다.`
              : `이번 단원에서는 ${a.best} 과목을 공부하였습니다. 다음 단원에서도 지금처럼 이어 가면 좋겠습니다.`,
          subjectEven: () => '이번 단원에서는 여러 과목을 고르게 공부하였습니다. 다음 단원에서도 지금처럼 이어 가면 좋겠습니다.',
          pending: () => '퀴즈 확인과 평가 문항 채점이 끝나면 역량과 과목의 기록이 채워집니다.',
        },
      },
      errors: {
        forbidden: '이 학생의 리포트를 저장할 수 없습니다.',
        notFound: '학생이나 단원을 찾을 수 없습니다.',
        noAssignments: '이 단원에서 이 학생에게 배정된 세트가 없습니다.',
        invalid: '리포트 모양이 올바르지 않아 저장하지 않았습니다.',
        saveFailed: '저장하지 못했습니다. 리포트 저장 칸이 아직 준비되지 않았을 수 있습니다. 미리보기와 인쇄는 그대로 할 수 있습니다.',
        noReport: '저장된 리포트가 없습니다.',
        loadFailed: '기록을 읽지 못해 저장하지 않았습니다. 잠시 뒤에 다시 눌러 주세요.',
        alreadyConfirmed: '이미 확정한 리포트입니다. 고치려면 [다시 고치기]를 눌러 주세요.',
      },
    },
  },
  // 교과융합 탐구보고서(설계 docs/superpowers/specs/2026-09-30-inquiry-report-design.md) — 본사가 과제를 만들고, 원장이 배정하고, 학생이 칸에 쓴다.
  // 대상은 초·중학생이라 길잡이 질문은 쉬운 말로. 내용은 한 줄에 하나, 옆으로 잇지 않는다.
  inquiry: {
    docTitle: '교과융합 탐구보고서',
    level: { 초: '초등학교', 중: '중학교' } as Record<'초' | '중', string>,
    kind: { paper: '논문', news: '기사', book: '도서' } as Record<'paper' | 'news' | 'book', string>,
    questionLabel: (key: string) => `탐구 문제 ${key}`,
    method: { none: '생략(실험·설문 없음)', survey: '설문', experiment: '실험', data: '자료 분석' } as Record<'none' | 'survey' | 'experiment' | 'data', string>,
    // 차례의 장 제목(로마 숫자는 lib/inquiry/outline.ts 가 붙인다)
    chapter: { intro: '서론', background: '이론적 배경', method: '탐구 방법', results: '탐구 결과', conclusion: '결론', reflection: '배우고 느낀 점', references: '참고문헌' } as Record<'intro' | 'background' | 'method' | 'results' | 'conclusion' | 'reflection' | 'references', string>,
    // 학생이 쓰는 칸: 제목 → 길잡이 질문(아랫줄) → 권장 분량(아랫줄). 과제의 section_guides 가 질문·분량을 덮어쓸 수 있다.
    section: {
      career: { title: '희망 진로', guide: '앞으로 하고 싶은 일이나 관심 있는 분야를 적어 보세요. 이 탐구와 어떻게 이어지는지도 한 줄 써 보면 좋아요.', length: '1~3줄' },
      motive: { title: '탐구 동기', guide: '이 주제가 왜 궁금했나요? 무엇을 보고 듣고 이 탐구를 시작하게 되었나요?', length: '5~8줄 (200~400자)' },
      questions: { title: '탐구 문제', guide: '이 보고서에서 답하려는 질문 세 개예요. 그대로 두어도 되고, 내 말로 조금 고쳐도 돼요.', length: '문제마다 한 문장' },
      background: { title: '이론적 배경', guide: '탐구 문제를 이해하려면 먼저 알아야 하는 낱말과 사실을 정리해요. 자료에서 읽은 내용을 내 말로 쓰고, 어느 자료에서 읽었는지 적어요.', length: '10~15줄 (400~700자)' },
      method: { title: '탐구 방법', guide: '무엇을, 어떻게 조사했는지 순서대로 써요.', length: '5~10줄 (200~400자)' },
      result: { title: (key: string) => `탐구 결과 ${key}`, guide: '이 문제에 대한 답을 쓰세요. 자료에서 찾은 근거(수치·사례·문장)를 들고, 어느 자료에서 찾았는지 적어요.', length: '10~15줄 (400~700자)' },
      conclusion: { title: '결론', guide: '세 문제의 답을 한 번에 정리해요. 이번 탐구에서 아쉬웠던 점(한계)을 한 줄 쓰고, 앞으로 하면 좋을 것을 제안해요.', length: '8~12줄 (300~500자)' },
      reflection: { title: '배우고 느낀 점', guide: '탐구하면서 새로 알게 된 것, 어려웠던 것, 생각이 달라진 것을 써요. 결론과 다른 내용이어야 해요.', length: '5~8줄 (200~400자)' },
      references: { title: '참고문헌', guide: '읽은 자료에 체크하면 참고문헌이 자동으로 만들어져요.', length: '' },
    },
    // 탐구 방법을 골랐을 때의 길잡이 질문(방법마다 다르다)
    methodGuide: {
      survey: '누구에게, 몇 명에게, 어떤 질문을 했나요? 언제 어디에서 했나요?',
      experiment: '무엇을 준비했고, 어떤 순서로 실험했나요? 무엇을 바꾸고 무엇을 같게 두었나요?',
      data: '어떤 자료를 골랐고, 왜 그 자료인가요? 자료에서 무엇을 어떻게 비교했나요?',
    } as Record<'survey' | 'experiment' | 'data', string>,
    // 배정 상태
    assignmentStatus: { assigned: '작성 중', submitted: '제출함', reopened: '다시 쓰는 중' } as Record<'assigned' | 'submitted' | 'reopened', string>,
    unavailable: '탐구보고서 저장 칸이 아직 준비되지 않았습니다. 대표님이 마이그레이션 0016 을 적용하면 열립니다.',
    // 게시 조건(설계 §4) — 자료의 진위에 관한 것만 막는다
    gate: {
      heading: '게시하려면 아직 필요한 것',
      papers: (n: number) => `확인함 표시가 있는 논문이 ${n}편 더 필요합니다(2편 이상).`,
      news: '확인함 표시가 있는 기사가 1건 이상 필요합니다.',
      book: '확인함 표시가 있는 도서가 1권 이상 필요합니다.',
      question: (key: string) => `탐구 문제 ${key}에 붙은 확인된 자료가 없습니다.`,
      title: '제목이 비어 있습니다.',
      subjects: '과목을 2개 이상 골라 주세요.',
      questionText: (key: string) => `탐구 문제 ${key}의 문장이 비어 있습니다.`,
      sourceIncomplete: (title: string) => `확인함 표시가 있는 자료 「${title}」에 제목·URL이 빠져 있습니다.`,
    },
    admin: {
      title: '탐구보고서 과제',
      help: '과제를 만들고 자료를 확인한 뒤 게시하면 원장님 화면에 나타납니다.',
      newButton: '새 과제',
      empty: '아직 과제가 없습니다. [새 과제]를 눌러 시작하세요.',
      status: { draft: '초안', published: '게시됨' } as Record<'draft' | 'published', string>,
      sourcesCount: (verified: number, total: number) => `자료 ${total}개 · 확인함 ${verified}개`,
      open: '열기',
      untitled: '(제목 없음)',
      page: {
        back: '← 과제 목록으로',
        help: '위에서 아래로 채우고 [저장]을 누르세요. 자료마다 URL을 열어 본 뒤 「확인함」에 체크하면 게시할 수 있습니다.',
        basicHeading: '기본 정보',
        titleLabel: '제목(질문형)', subtitleLabel: '부제', levelLabel: '대상', subjectsLabel: '융합 과목(2개 이상)', themeLabel: '서논술 대주제(선택)', themeNone: '연결 안 함',
        questionsHeading: '탐구 문제',
        questionsHelp: '문제 세 개는 가·나·다 순서 그대로 학생의 탐구 결과 칸이 됩니다.',
        questionText: '문제', questionLens: '보는 눈(예: 사회의 눈 / 국어의 눈 / 융합)',
        sourcesHeading: '자료',
        sourcesHelp: '논문 2편 이상, 기사 1건 이상, 도서 1권 이상. 확인함에 체크한 자료만 학생과 원장님에게 보입니다.',
        addSource: '자료 추가',
        removeSource: '이 자료 빼기',
        sourceKind: '종류',
        sourceFields: { title: '제목', authors: '저자(기자)', year: '연도', date: '날짜(기사, YYYY-MM-DD)', container: '학술지·매체·출판사', detail: '권(호)·쪽 등', url: 'URL', note: '비고(학술대회 발표문 등)', easySummary: '쉬운 요약(학생용 2~3문장)' },
        excerptsHeading: '발췌(본문을 보고 넣습니다 — 비워 두어도 됩니다)',
        excerptText: '발췌 문장(2~3문장)', excerptLocator: '출처(쪽·문단)', addExcerpt: '발췌 추가', removeExcerpt: '빼기',
        forQuestions: '이 자료를 쓰는 탐구 문제',
        verified: '확인함 — URL을 열어 제목·저자·서지를 확인했습니다',
        verifiedBy: (by: string, at: string) => `${by} · ${at} 확인`,
        openUrl: '링크 열기',
        tipsHeading: '지도할 때 짚을 점(한 줄에 하나)',
        tipsHelp: '원장님 화면에 그대로 보입니다.',
        guidesHeading: '칸 길잡이 덮어쓰기(선택)',
        guidesHelp: '비워 두면 기본 길잡이 질문과 권장 분량이 쓰입니다.',
        guideQuestion: '길잡이 질문', guideLength: '권장 분량',
        importHeading: 'JSON 불러오기',
        importHelp: '과제 파일(data/inquiry/*.json)의 내용을 붙여넣고 [불러오기]를 누르면 이 과제에 채워집니다. 확인함 표시는 채우지 않습니다.',
        importButton: '불러오기', importing: '불러오는 중…', imported: '불러왔습니다. 자료마다 링크를 열어 확인한 뒤 「확인함」에 체크해 주세요.',
        save: '저장', saving: '저장 중…', saved: '저장했습니다.',
        publish: '게시', unpublish: '게시 취소', published: '게시했습니다. 원장님 화면에 보입니다.', unpublished: '게시를 취소했습니다.',
        publishedAt: (at: string) => `게시 ${at}`,
        unsaved: '고친 내용이 있습니다. [저장]을 눌러 주세요.',
        gateOk: '게시 조건을 모두 갖췄습니다.',
      },
      errors: {
        forbidden: '본사 관리자만 할 수 있습니다.',
        notFound: '과제를 찾을 수 없습니다.',
        invalid: '입력 모양이 올바르지 않아 저장하지 않았습니다.',
        invalidJson: 'JSON을 읽지 못했습니다. 파일 내용을 그대로 붙여넣었는지 확인해 주세요.',
        saveFailed: '저장하지 못했습니다. 잠시 뒤에 다시 눌러 주세요.',
        gate: '게시 조건이 아직 갖춰지지 않았습니다. 아래 목록을 확인해 주세요.',
      },
    },
    teacher: {
      title: '탐구보고서',
      help: '과제를 고르고 학생을 배정하면 학생이 칸에 씁니다. 목차는 그대로 두고 [확인]만 눌러도 됩니다.',
      empty: '아직 게시된 탐구보고서 과제가 없습니다.',
      assignButton: '학생 배정',
      assignedCount: (n: number) => `우리 원 배정 ${n}명`,
      subjectsLine: (subjects: string[]) => `융합 과목: ${subjects.join(' · ')}`,
      levelLine: (level: string) => `대상: ${level}`,
      page: {
        back: '← 과제 목록으로',
        help: '① 학생을 체크하고 [배정] → ② 목차는 기본값 그대로 [확인] → ③ 아래 현황에서 [보고서 보기].',
        taskHeading: '과제',
        questionsHeading: '탐구 문제',
        sourcesHeading: '학생에게 보이는 자료',
        sourceLine: (kind: string, title: string) => `[${kind}] ${title}`,
        tipsHeading: '지도할 때 짚을 점',
        assignHeading: '학생 배정',
        assignHelp: '체크한 학생에게 이 과제가 열립니다. 이미 배정된 학생은 상태만 보입니다.',
        selectAll: '모두 선택',
        noStudents: '등록된 학생이 없습니다. 학생 관리에서 먼저 추가해 주세요.',
        assign: '배정', assigning: '배정 중…', assigned: (n: number) => `${n}명에게 배정했습니다.`,
        outlineHeading: '목차',
        outlineChangeHeading: '목차 바꾸기 (배정한 뒤에 바꿀 때만)',
        outlineHelp: '실험이나 설문을 하지 않으면 「탐구 방법」은 생략합니다(기본값). 바꾸지 않아도 되면 [확인]만 누르세요.',
        methodLabel: '탐구 방법', careerLabel: '희망 진로 칸 넣기',
        outlinePreview: '학생이 보게 될 차례',
        applyTo: '적용할 학생',
        confirm: '확인', confirming: '적용 중…', confirmed: (n: number) => `${n}명의 목차를 확인했습니다.`,
        outlineNoAssignments: '먼저 학생을 배정하면 목차를 확인할 수 있습니다.',
        progressHeading: '작성 현황',
        progressLine: (filled: number, total: number) => `${total}칸 중 ${filled}칸 작성`,
        updatedAt: (at: string) => `마지막 저장 ${at}`,
        submittedAt: (at: string) => `제출 ${at}`,
        openReport: '보고서 보기',
        noProgress: '아직 배정한 학생이 없습니다.',
      },
      report: {
        back: '← 배정 화면으로',
        title: (name: string) => `${name} 학생 탐구보고서`,
        help: '학생이 쓴 그대로입니다. [인쇄]로 종이 보고서를 뽑고, 고칠 것이 있으면 [다시 쓰게 하기]를 누르세요.',
        print: '인쇄', reopen: '다시 쓰게 하기', reopening: '여는 중…', reopened: '학생이 다시 쓸 수 있습니다.',
        notSubmitted: '아직 제출 전입니다. 지금까지 쓴 내용이 보입니다.',
        empty: '학생이 아직 쓰기 시작하지 않았습니다.',
      },
      errors: {
        forbidden: '우리 원의 배정만 볼 수 있습니다.',
        notFound: '과제나 배정을 찾을 수 없습니다.',
        noStudents: '학생을 한 명 이상 체크해 주세요.',
        saveFailed: '저장하지 못했습니다. 잠시 뒤에 다시 눌러 주세요.',
        notPublished: '게시되지 않은 과제입니다.',
      },
    },
    student: {
      title: '탐구보고서',
      help: '칸마다 길잡이 질문을 읽고 차례대로 써요. 쓰는 동안 저절로 저장돼요.',
      empty: '아직 배정된 탐구보고서가 없어요.',
      card: { write: '쓰기', view: '보기', progress: (filled: number, total: number) => `${total}칸 중 ${filled}칸 썼어요` },
      page: {
        back: '← 내 탐구보고서로',
        help: '위에서 아래로 차례대로 써요. 다 쓰면 맨 아래 [제출]을 눌러요.',
        subjectsLine: (subjects: string[]) => `융합 과목: ${subjects.join(' · ')}`,
        guideLabel: '길잡이', lengthLabel: '권장 분량',
        chars: (n: number) => `${n}자`,
        maxChars: (n: number, max: number) => `${n}/${max}자`,
        saving: '저장 중…', saved: (hhmm: string) => `저장됨 ${hhmm}`, saveFailed: '저장하지 못했어요. 잠시 뒤에 다시 써 보세요.',
        placeholder: '여기에 써요.',
        questionPlaceholder: (key: string) => `탐구 문제 ${key}`,
        resultQuestion: '이 칸의 탐구 문제',
        sourcesFor: '이 문제에 쓰는 자료',
        sourceSummary: '쉬운 요약', sourceExcerpts: '발췌', sourceLocator: (l: string) => `(${l})`, openSource: '자료 열기(새 창)',
        referencesHelp: '읽은 자료에 체크해요. 체크한 자료가 참고문헌에 들어가요.',
        readIt: '읽었어요',
        referencesPreview: '참고문헌 미리보기',
        referencesNone: '아직 체크한 자료가 없어요.',
        submit: '제출', submitting: '제출 중…',
        submitConfirm: '제출하면 더 고칠 수 없어요. 원장님이 다시 열어 주시면 고칠 수 있어요. 제출할까요?',
        submitted: '제출했어요.',
        submittedNote: '제출한 보고서예요. 고치고 싶으면 원장님께 말씀드려요.',
        reopenedNote: '원장님이 다시 열어 주셨어요. 고친 뒤 다시 [제출]을 눌러요.',
        myReport: '내 보고서',
        emptyBoxes: (n: number) => `아직 비어 있는 칸이 ${n}개 있어요. 그래도 제출할 수 있어요.`,
      },
      errors: {
        forbidden: '내 과제만 쓸 수 있어요.',
        notFound: '과제를 찾을 수 없어요.',
        submitted: '이미 제출한 보고서예요.',
        saveFailed: '저장하지 못했어요.',
        invalid: '글이 너무 길거나 모양이 맞지 않아요.',
      },
    },
    // 인쇄·보기(components/inquiry/InquiryReportView)
    view: {
      coverLabel: '교과융합 탐구보고서',
      coverFields: { grade: '학년', klass: '반', number: '번호', name: '이름' },
      subjectsLine: (subjects: string[]) => `융합 과목: ${subjects.join(' · ')}`,
      careerLine: (career: string) => `희망 진로: ${career}`,
      tocHeading: '차례',
      chapterNo: (roman: string, title: string) => `${roman}. ${title}`,
      sectionNo: (n: number, title: string) => `${n}. ${title}`,
      emptySection: '(아직 쓰지 않았습니다)',
      referencesNone: '(체크한 자료가 없습니다)',
      academyLine: (name: string) => name,
    },
  },
  // 제본용 교재(설계 docs/superpowers/specs/2026-10-01-booklet-design.md, 대표 2026-10-01): 학생용 교재(답 없음)·교사용 지도서(답 있음).
  // 세트 화면(원장 문항·본사 세트)의 두 단추 → 인쇄 전용 쪽(/…/book/student·/…/book/teacher) → 브라우저 인쇄. 학생·학부모에게는 보이지 않는다.
  // 자료 라벨(<자료 n>)·평가 요소 줄·퀴즈 유형·분량/형식 같은 문구는 packageView 의 키를 그대로 쓴다(문제지와 같은 말).
  book: {
    buttons: { student: '학생용 교재 인쇄', teacher: '교사용 지도서 인쇄' },
    print: '인쇄',
    close: '닫기',
    draftMark: '초안 미리보기',
    kindTitle: { student: '학생용 교재', teacher: '교사용 지도서' } as Record<'student' | 'teacher', string>,
    // 쪽 번호는 브라우저가 인쇄할 때 아래 가운데에 매긴다(app/globals.css @page book) — 화면에는 이 한 줄만
    pageNumbersNote: '쪽 번호는 인쇄할 때 브라우저가 아래 가운데에 매깁니다.',
    cover: {
      teacherMark: '교사용',
      subjectLine: (level: string, grade: number | null, subject: string) => `${levelGradeLong(level, grade)} · ${subject}`,
      versionLine: (v: number) => `${v}판`,
      fields: { grade: '학년', klass: '반', number: '번호', name: '이름' },
      academy: '다빈치스쿨',
    },
    toc: { heading: '차례', lessonsLabel: '차시' },
    unit: {
      heading: '이 단원에서',
      keyQuestion: '핵심 질문',
      goals: '배울 것',
      criteria: '평가 요소',
      criteriaItem: (no: number, kind: string) => `${no}번 ${kind}`,
    },
    lesson: {
      heading: (no: number, topic: string) => (topic ? `${no}차시 ${topic}` : `${no}차시`),
      goal: '배울 내용',
      keyQuestion: '핵심 질문',
      materials: '이 차시 자료',
      materialLabel: (id: string) => `자료 ${id}`,
      worksheet: '활동지',
      taskNo: (no: number) => `${no}.`,
      tier: (tier: string) => tier,
      selfCheck: '자기평가',
      selfCheckBox: '□',
      quiz: '퀴즈',
      quizNo: (no: number) => `${no}.`,
      answerLabel: '답',
      // 교사용
      flow: '수업 흐름',
      flowStep: { intro: '도입', main: '전개', wrapup: '정리' },
      minutes: (n: number) => `${n}분`,
      script: '교사 발문과 예상 답',
      expected: '예상 답',
      stuck: '막힐 때 도움말',
      worksheetAnswers: '활동지 정답·예시 답',
      quizAnswers: '퀴즈 정답·해설',
      quizAnswer: '정답',
      quizExplanation: '해설',
      competency: (c: string) => `역량: ${c}`,
      quizLevel: (lv: string) => `수준 ${lv}`,
      needs: '준비물',
      cautions: '유의점',
      guideNotes: '지침서 메모',
      mergeNote: '병합 시 생략',
      mergeable: (no: number) => `${no}차시와 병합 가능`,
      standards: '성취기준',
    },
    assessment: {
      heading: '단원 평가',
      intro: '자료를 읽고 문항에 답하세요.',
      itemNo: (no: number) => `${no}.`,
      kindPoints: (kind: string, points: number) => `${kind} · ${points}점`,
      conditions: '조건',
      conditionNo: (no: number) => `조건 ${no}.`,
      conditionPoints: (p: number) => `(${p}점)`,
      length: '분량',
      format: '형식',
      overflow: '초과 응답',
      answerSpace: '답안',
      paperBox: '종이 답안 — 이 칸에 직접 쓰거나 그리세요.',
      // 교사용
      sessionFlow: '평가 차시 운영',
      intent: '출제 의도',
      situation: '과제 상황',
      linkedLesson: (no: number) => `${no}차시 연계`,
      rubric: '채점 기준',
      criterion: (name: string, max: number) => `${name} (0~${max}점)`,
      taughtIn: (nos: number[]) => `배운 차시: ${nos.join('·')}차시`,
      scalePoints: (p: number) => `${p}점`,
      scaleExample: '예',
      holistic: '총체적 기준',
      notes: '채점 시 유의점',
      exemplars: '예시 답안',
      exemplarLabel: (level: string | null, points: number) => `${level ?? ''} ${points}점`.trim(),
      exemplarScores: (scores: number[]) => `요소별 ${scores.join('·')}`,
      rationale: '채점자 의견',
      levelMap: '수준 지도(A~E)',
      minCompetency: '최소 능력',
      gradeBoundaries: '등급 경계표',
      gradeColumns: { grade: '등급', range: '점수 범위', band: '수준', levelRef: '수준 참조' },
      feedback: '피드백 틀',
    },
    plan: {
      heading: '단원 계획',
      standards: '성취기준',
      original: '원문',
      reconstructed: (type: string) => `재구성(${type})`,
      sameAsOriginal: '원문 그대로',
      reconstructionNote: '재구성 설명',
      goals: '학습 목표(3차원)',
      keyQuestion: '핵심 질문',
      table: '차시 구성표',
      columns: { no: '차시', topic: '주제', materials: '자료', assessment: '평가' },
      quizCell: (n: number) => `퀴즈 ${n}문항`,
      none: '-',
      formative: '형성평가',
    },
    guide: { heading: '교사용 지침' },
    notice: { heading: '안내장 틀' },
    back: { heading: '뒤표지', note: '이 교재는 다빈치스쿨 서논술형 수업용입니다.' },
  },
}

export const email = {
  inquiry: {
    // Resend에서 davinci-lab.kr 도메인 인증 후 lib/email/config.ts 의 주소를 교체할 때 이 표시 이름을 쓴다.
    fromName: '다빈치스쿨',
    subject: (region: string, name: string) => `[가맹문의] ${region} ${name}`,
    labels: { name: '이름', phone: '연락처', region: '지역' },
  },
}

export const pages = {
  comingSoon: {
    eyebrow: 'COMING SOON',
    title: (name: string) => `${name}은(는) 준비 중입니다`,
    body: '곧 자세한 안내를 드리겠습니다.',
    back: '메인으로',
  },
  program: {
    cta: '이 수업으로 가맹 문의',
  },
  franchise: {
    title: '다빈치스쿨 가맹 안내',
    intro: '본사가 교재·문항·교사용 지침서·AI 채점 시스템을 제공합니다. 원장님은 학생과 수업에 집중하세요.',
    formTitle: '문의 남기기',
    fields: {
      name: { label: '이름' },
      phone: { label: '연락처', placeholder: '010-0000-0000' },
      region: { label: '지역', placeholder: '예: 경기 성남' },
      message: { label: '문의 내용' },
    },
    submit: '문의 보내기',
    submitting: '보내는 중…',
    success: {
      title: '문의가 접수되었습니다',
      body: '본사에서 1~2일 안에 연락드리겠습니다.',
    },
    errors: {
      name: '이름을 입력하세요.',
      phone: '연락처를 확인하세요.',
      region: '지역을 입력하세요.',
      generic: '입력을 확인하세요.',
      submitFailed: '접수 중 오류가 났습니다. 잠시 후 다시 시도해 주세요.',
    },
  },
}
